### ISSUE TITLE
Library does not support tokens

### ISSUE THREAD

**Issue by trumpCoder** [SinisterRectus/Discordia#100]
After installing Lua, I get this error:
``Could not authenticate, check token: HTTP Error 0 : 401: Unauthorized``

**However, my token is indeed correct.**

**Comment by DannehSC** [comment]
Did you prefix your token with "Bot "

**Comment by trumpCoder** [comment]
No. I don't see why that's necessary.

**Comment by trumpCoder** [comment]
Tokens do NOT begin with "Bot". I'm pasting my token from the discord development page.

**Comment by DannehSC** [comment]
Just prefix the token. It's necessary.

**Comment by trumpCoder** [comment]
Ok, I put ``BotMzcwNzRxNjgyMjgyOTg2NDk6.DTKTmA.yxl3IoLd-zUsyWpAFYJb9ogNpM``

Same error.

**Comment by DannehSC** [comment]
Space between "Bot" and your token. And go reset it.

**Comment by trumpCoder** [comment]
Fuck, okay, I edited my token out.

**Comment by trumpCoder** [comment]
Same error.

Format used: ``Bot token``

**Comment by DannehSC** [comment]
Single space. And just editing it doesn't help you have to reset it

**Comment by trumpCoder** [comment]
I went to the Discord application page and my token is different, so I assume it's already reset.

My format used uses a single space.

**Comment by DannehSC** [comment]
No. You have to expressly hit token reset. And let me just provide an example.
```Lua
local token = "token here"
client:run("Bot "..token)

**Comment by trumpCoder** [comment]
Fixed as of https://github.com/SinisterRectus/Discordia/issues/100

**Comment by trumpCoder** [comment]
Fixed as of https://github.com/SinisterRectus/Discordia/pull/101

**Comment by jhonny-papallom** [comment]
Check my last comment at #96
