### ISSUE TITLE
Another issue - can't send messages

### ISSUE THREAD

**Issue by trumpCoder** [SinisterRectus/Discordia#102]
After my bot successfully logged in, this code errors:

``message.channel.send("Hello, I am alive!")``

Not sure why. This is correct Lua syntax and I followed the documentation.

**Comment by trumpCoder** [comment]
Edit: forgot to include the error message.

Something about _parent being nil

**Comment by trumpCoder** [comment]
Possible solution: define _parent to be the channel.

**Comment by trumpCoder** [comment]
Let me fix this and submit a PR.

**Comment by trumpCoder** [comment]
Actually, I will do that tomorrow. Time for bed.

**Comment by PurgePJ** [comment]
I think you should stop talking to yourself 😊
You are spamming a lot in GitHub. Please move to DiscordAPI server and talk there with us.

**Comment by Lautenschlager-id** [comment]
It's message.channel:send(content)

**Comment by SinisterRectus** [comment]
Not a bug. Use semi-colon syntax for class member method calls.
