### ISSUE TITLE
cannot load module opus and sodium

### ISSUE THREAD

**Issue by Fezezen** [SinisterRectus/Discordia#103]
First of all sorry if someone's already asked something like this, but I couldn't find anything about this else where. I have the voice library and I have checked the directory and opus.lua and sodium.lua are both in the voice file, one example I've looked had "client.voice:loadOpus()" and "client.voice:loadSodium()". Is there some sort of software I need to get? Did I do something wrong or is the code just broken?https://gyazo.com/588e08c9c43c1f0ae35373a1fb954bca

**Comment by SinisterRectus** [comment]
You need libsodium and libopus either in your main directory or installed on your OS. In any case, voice is currently not supported since it's still under development.

**Comment by Fezezen** [comment]
I'm on windows if this changes your reply, by main directory what do you mean? Sorry for asking

**Comment by SinisterRectus** [comment]
The directory where you're running your bot. You need opus.dll and sodium.dll, if you can find them online or build them yourself. You won't be able to do much with voice, though, other than join a voice channel.

**Comment by Fezezen** [comment]
Alright thanks

**Comment by Fezezen** [comment]
I still get the error, but the bot can still connect to the server, everyone's just gonna use a different bot anyway
