### ISSUE TITLE
Issue with SetUsername

### ISSUE THREAD

**Issue by 360n** [SinisterRectus/Discordia#106]
So, this is my code:
`if message.content:find('!name ') and message.author == client.owner then`
`daname = message.content:sub(7)`
`client:setUsername(daname)`
`end`
But when I try and use the command in discord, this shows up in the command prompt:
` [ERROR]   | 400 - BAD REQUEST : PATCH https://discordapp.com/api/v7/users/@me`
But the strange thing is, if I replace `setUsername` with `setGame` it works perfectly fine with setting the bot's game.

**Comment by SinisterRectus** [comment]
What is returned by the function?

**Comment by Tigerism** [comment]
If it's saying bad request, then Discord is not allowing the username change. Print to see what is "danname" and make sure it looks valid. This is not a problem with the library.

**Comment by 360n** [comment]
Sorry to bother you guys, it's suddenly started working? Strange. Anyway, thanks for your help.
