### ISSUE TITLE
Bot always disconnects unexpectedly on launch.

### ISSUE THREAD

**Issue by Lexxic** [SinisterRectus/Discordia#107]
Whenever I run any bot on any token, it 
![error](https://user-images.githubusercontent.com/31022887/36461148-108768b6-168a-11e8-9715-541d130221e6.png)
Does anyone know of a fix and/or way around this?

**Comment by Lexxic** [comment]
It repeats it ad nauseam as soon as I run it.

**Comment by truemedian** [comment]
Update discordia by deleteing it's directory in deps and reinstall with `lit install SinisterRectus/discordia`

**Comment by Lexxic** [comment]
Thanks!
