### ISSUE TITLE
Impossible to inspect/modify discordia's event handlers at runtime.

### ISSUE THREAD

**Issue by Mehgugs** [SinisterRectus/Discordia#117]
This became apparent when writing my Lavalink client, it needs to be able to redirect `VOICE_SERVER_UPDATE` from the discordia client to it's own handler. The `EventHandler` that the shards use is currently internal and required as necessary by the internal components of discordia. 

I have 2 ideas right now:
A.) Making `VoiceManager` responsible for all the `EventHandler.VOICE_SERVER_UPDATE` code, that way one can replace `client._voice` at runtime. 
B.) Making `get.events` available for the `Client` class: 
```lua
function get.events(self)
	return EventHandler
end
```
This would allow cleaner modification of the event without modifying what the lib and users expect `client._voice` to be but then makes a lot of other events easy to modify which is not something users should be doing normally.

**Comment by SinisterRectus** [comment]
I'm reluctant to allow runtime editing of the event handlers, but I can see why it is preferable to editing the source. Let me think about this.

**Comment by SinisterRectus** [comment]
I don't see any reason to expose events that would benefit the average user. Modify the code before runtime.

**Comment by Mehgugs** [comment]
I dont want to edit someone's discordia installation because the EventHandler is an internal part of the code, unless there's a better which I'm not seeing (and don't say debug.getLocal)

**Comment by SinisterRectus** [comment]
Then why modify it at runtime?

**Comment by Mehgugs** [comment]
Because I need to make discordia's shards not handle the voice events because lavalink does and there's not a way to do that in discordia hence I added a way to access `EventHandler` from client in my local branch in order to progress, but I dont want to maintain that branch as the version of discordia you need. Other libs either just change the raw event handler or their lib's voice code handles it in a way that they just replace the voice connection/client with their own. 
Ideally replacing the voice modules is the way to go , but `GuildVoiceChannel` only deals with the discordia connections so I cant do something like `client._voice = MyVoiceManager`  because the discordia object is baked in to the channel code.

**Comment by SinisterRectus** [comment]
I've added an internal property. Use at your own risk fbf62e23d1d1aee6981cd2d53379715e9ee509fa.
