### ISSUE TITLE
Message Deleting Takes Its Time

### ISSUE THREAD

**Issue by GlitchKing79** [SinisterRectus/Discordia#123]
i made a basic loop through a table of messages and compared to other discord bot api's it seems discordia does it slowly. Am i doing something wrong or is the message table (message.channel:getMessages(100)) still being work through or just slow

**Comment by Mishio595** [comment]
Invalid issue. Discordia follows Discord's rate limits. The "slowing" you are experiencing is Discord rate-limiting your request. If you need to delete large quantities of messages, use bulkDelete.

**Comment by supersonicfan111** [comment]
bulkDelete doesn't support numbers, only a table, which means that we, well, basically can't without :getMessages().

**Comment by Mishio595** [comment]
1) This is intentional. Previous versions of discordia took numbers and it provided less flexibility. It was changed to accepting either a cache of messages or a table of message IDs.
2) That is unrelated to the issue.

**Comment by SinisterRectus** [comment]
How slowly are you deleting messages? What speed do you expect?

**Comment by GlitchKing79** [comment]
ok  so i should have said this earlier, but thank you Mishio595 for sending me in the right direction, and for those who come here again im supplying code that works with bulk deleting (100+ even though ineffiecient) 
`if commands[1] == '/clean' then
		if commands[2] ~= nil then
			local numb = tonumber(commands[2])
			if numb ~= nil then
				if numb <= 100 then
					local mg = message.channel:getMessages(numb)
					message.channel:bulkDelete(mg)
				else
					local tmsg = numb/100
					local endingMsg = tmsg % 1
					local totalMsg = tmsg - endingMsg
					for i=1, totalMsg do
						mg = message.channel:getMessages(100)
						message.channel:bulkDelete(mg)
					end
					mg = message.channel:getMessages(100 * endingMsg)
					message.channel:bulkDelete(mg)
				end
			end
		else
			local mg = message.channel:getMessages(100)
			message.channel:bulkDelete(mg)
		end
	end`
commands is a table of each word sent into the channel

**Comment by SinisterRectus** [comment]
I can't attest to the efficiency of that code, but if it works for you, then great.
