### ISSUE TITLE
The tutorial errors.

### ISSUE THREAD

**Issue by smaltin-rules** [SinisterRectus/Discordia#126]
I am making sure the library works. I put in my code...
```
local discordia = require('discordia')
local client = discordia.Client()

client:on('ready', function()
	print('Logged in as '.. client.user.username)
end)

client:on('messageCreate', function(message)
	if message.content == '!ping' then
		message.channel:send('Pong!')
	end
end)

client:run('Bot >insert code here<')
```
and then I run `luvit bot.lua`.

What I get is...
```
2018-05-13 20:45:31 | [INFO]    | Discordia 2.3.0
2018-05-13 20:45:31 | [INFO]    | Connecting to Discord...
2018-05-13 20:45:32 | [ERROR]   | 401 - UNAUTHORIZED : GET https://discordapp.com/api/v7/users/@me
2018-05-13 20:45:32 | [ERROR]   | Could not authenticate, check token: HTTP Error 0 : 401: Unauthorized
```

Any help with this issue? Am I doing something wrong?

**Comment by Mishio595** [comment]
Either your token is invalid or you need to delete and reinstall discordia.

**Comment by Kore-Development** [comment]
I don't know if it's the cause of the problem but `locallocal discordia discor` should be `local discordia`

**Comment by smaltin-rules** [comment]
@Kore-Development That was not the problem, just a little mistake I made inside my editor. Still produces the same effect.

**Comment by Mishio595** [comment]
This is not an issue with the tutorial.

For further questions, please join the discord channel #lua-discordia in the discord API guild. https://discord.gg/discord-api

**Comment by smaltin-rules** [comment]
I found out why, and it was my fault. I had 2 instances of bot.lua in 2 different places, and I wasn't updating the one I was using. You can ignore everything, I messed up.
