### ISSUE TITLE
Game Object

### ISSUE THREAD

**Issue by Dog2puppy** [SinisterRectus/Discordia#13]
So what's this game object in TODO.md

**Comment by logandark** [comment]
Supposedly a game object to set your status to.

**Comment by SinisterRectus** [comment]
In the live version (0.6) of Discordia, your "now playing" status is parsed as a `gameName` attribute. Internally, Discord uses a game object, with room for more than just the name. Future versions of Discordia should use an object to be more consistent with what is provided internally. The rewrite currently has it as a [Lua table](https://github.com/SinisterRectus/Discordia/blob/e6f918c469525e8985fe94a0c2b025d419de6172/discordia/containers/snowflakes/Member.lua#L40), but not a class instance.

If you have further questions, feel free to drop by our [Discord channel](https://discord.gg/0SBTUU1wZTWVpm07).
