### ISSUE TITLE
Conflict with Luvit HTTP server

### ISSUE THREAD

**Issue by MikuAuahDark** [SinisterRectus/Discordia#130]
When I install Discordia, Luvit HTTP server cease to function.

```lua
-- HTTP server for quit
local http = require("http")
http.createServer(function (req, res)
	print(req, res)
	res.statusCode = 204
	res.statusMessage = ""
	res:setHeader("Content-Length", 0)
	res:finish()
end):listen(7676, "0.0.0.0")
print("test")
```

And when I do `curl -v http://localhost:7676`, there's no output and the cURL hangs.

I tried to put the code outside the bot directory (so Luvit default library is used) and the code runs correctly.

Can this be fixed? I would like to control my bot with some kind of HTTP request.

**Comment by MikuAuahDark** [comment]
When I run that simple HTTP web server code in my bot dir (where Discordia
present as deps), it listens successfully, but it can't respond any message
(cURL hangs).

Should I try again by redownloading Discordia in different directory?

Pada tanggal Sab, 30 Jun 2018 04.25, Adelyn <notifications@github.com>
menulis:

**Comment by truemedian** [comment]
Discordia should have nothing to do with the bultin http module, try redownloading the luvit executable and try with that.

**Comment by MikuAuahDark** [comment]
Not sure by redownloading Luvit executable because the code works when it's
placed outside bot directory.

Pada tanggal Sab, 30 Jun 2018 08.40, Nameless <notifications@github.com>
menulis:

**Comment by truemedian** [comment]
Discordia should in no way be affecting the builtin http library. Make sure there isnt anything in deps overwriting the builtin library.

**Comment by Mishio595** [comment]
Like I said, we are unable to reproduce your issue. If you can provide more information, we may be able to assist more. Currently, you haven't specified if your bot dir has other dependencies, or if your bot code itself is causing some kind of issue. In my example I did exactly what you described and it worked without issues.

**Comment by MikuAuahDark** [comment]
Hmm, looks like resetting the dependencies fixes the problem.
