### ISSUE TITLE
Guild, a nil value

### ISSUE THREAD

**Issue by SamBehner** [SinisterRectus/Discordia#144]
Whenever I try to use guild, it returns a nil value: ex.

`value = "There are currently have "..tostring(guild.totalMemberCount) " members."`

returns
`attempt to index global 'guild' (a nil value)`

**Comment by SinisterRectus** [comment]
As the error message says, `guild` is nil. You need to define it.

**Comment by SamBehner** [comment]
How could I define it, im assuming I would have to reach it by something like

`local server = message.guild;`

**Comment by PurgePJ** [comment]
In your case it would be:

`local guild = message.guild`

and only if you are doing this with a message object (for example in messageCreate event).

**Comment by SamBehner** [comment]
yeah, I got it working with

`message.channel.guild`

**Comment by PurgePJ** [comment]
If you are receiving a message object, `guild` should be also accessible from `message.guild`. As docs state:

`The guild in which this message was sent. This will not exist if the message
was not sent in a guild text channel. Equivalent to Message.channel.guild`

**Comment by PurgePJ** [comment]
Also if the issue is resolved please close it 💃
