### ISSUE TITLE
Getting all members

### ISSUE THREAD

**Issue by SamBehner** [SinisterRectus/Discordia#147]
Hello, I am currently looking to make a few commands that run something on every member, how could i do this? something like:

`
client:on('messageCreated', function(msg)
    if msg.content == "./SetEveryonesRoleToMember" then 
        for k,v in ipairs(msg.channel.guild.members) do
            v:setRole(theMemberRoleThing) -- idk what it is rn
        end
    end
end)
`

But because it's cached and isn't a table,  this wont work, is there any other way I can do this?

**Comment by PurgePJ** [comment]
```lua
for member in msg.guild.members:iter() do
 member:setRole(...)
end
```

Caches can be looped with that. for more info [click here](https://github.com/SinisterRectus/Discordia/wiki/Cache).

**Comment by SamBehner** [comment]
Alright thanks!

**Comment by SamBehner** [comment]
Yep, that worked, thanks a lot!
