### ISSUE TITLE
acceptInvite question

### ISSUE THREAD

**Issue by TXMXenon** [SinisterRectus/Discordia#149]
If you removed the accept invite function what would I have to do to get my bot to join a server when it recognizes an invite code

**Comment by SinisterRectus** [comment]
Bots cannot accept invites. You must use an oauth2 url to add them to servers.

**Comment by TXMXenon** [comment]
I meant a selfbot, using a normal user account and token.

**Comment by SinisterRectus** [comment]
This is not possible anymore, sorry.

**Comment by PurgePJ** [comment]
Selfbots are not allowed by ToS.
