### ISSUE TITLE
Document Resolvers

### ISSUE THREAD

**Issue by Mehgugs** [SinisterRectus/Discordia#151]
This would be useful because it's not always clear, without looking in [`Resolver.lua`](https://github.com/SinisterRectus/Discordia/blob/master/libs/client/Resolver.lua), what a method can accept.

**Comment by SinisterRectus** [comment]
Yep.

**Comment by SinisterRectus** [comment]
https://github.com/SinisterRectus/Discordia/wiki/Input-resolution
