### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by hexando** [SinisterRectus/Discordia#154]
Hello, how can I make the bot respond to a separate user, like this:
![](https://i.imgur.com/jMESRhQ.jpg)

**Comment by LaevusDexter** [comment]
"Read docs" ©
https://github.com/SinisterRectus/Discordia/wiki/User
User:getPrivateChannel():send(content)

**Comment by Kore-Development** [comment]
Mention them

**Comment by Kore-Development** [comment]
If that's what you mean

**Comment by truemedian** [comment]
This question really has multiple answers and the only real answer is read the documentation, as it provides as much information as you need.

**Comment by Mehgugs** [comment]
The wiki topic on managing messages describes how to format your messages and the user documentation details how to get the mention string.

Please join the discord if you require more general help [here](https://discord.gg/NKM3XmF)

**Comment by Flamanis** [comment]
To add on, this is general help.


Also, hi discord peoples. I wanted to be a part of something.
