### ISSUE TITLE
`client:stop()` does not work inside a signal handler

### ISSUE THREAD

**Issue by odiferousmint** [SinisterRectus/Discordia#155]
Hello.

I am trying to execute `client:stop()` from the signal handler for SIGINT, and I get this error message:

```
error in signal handler 2: deps/coro-channel.lua:147: attempt to yield across C-call boundary
Uncaught exception: deps/coro-channel.lua:119: cannot resume running coroutine
stack traceback:
        [C]: in function 'assert'
        deps/coro-channel.lua:119: in function <deps/coro-channel.lua:118>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```

Code:

```lua
local function sighandler (signum)
  client:stop()
  os.exit(128 + signum)
end

signal.signal(signal.SIGINT, sighandler)
```

Any ideas?

**Comment by truemedian** [comment]
client:stop() needs to be ran inside a coroutine.

**Comment by odiferousmint** [comment]
On second thought, it doesn't make the bot go offline which I thought it would do. It still seems to just time out.

**Comment by Mishio595** [comment]
The bot will continue to appear online for 1-2 heartbeat cycles at which point Discord determines the connection is closed or lost and will label the app as offline. This is the same behaviour you can see when logging out of Discord as an actual user. If you want your bot to appear to go offline prior to shutting down, you must send a status update.

**Comment by SinisterRectus** [comment]
Discordia uses the coro-websocket library, which is undocumented and has few examples. I'm not sure if I am properly closing the connection, either by my own usage of the library or its implementation. In any case, if you need your bot to appear offline, you can set the status with `client:setStatus(discordia.enums.status.invisible)`.

And yes, you need to make sure this is executed in a coroutine.

**Comment by odiferousmint** [comment]
Thank you for the replies!
