### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by chexburger** [SinisterRectus/Discordia#157]
I was trying to do the commands thing. It refused to accept that I was running a command. I even tried copy pasting the entire example but even that didn't work. It'd be great if the page could be updated to work correctly. I am unsure what is wrong with it.

The bot will respond to the help command since it's in the messageCreate.

https://github.com/SinisterRectus/Discordia/blob/master/examples/basicCommands.lua

**Comment by truemedian** [comment]
The example provided works perfectly fine, are you sure that the bot is running and is in the server?

**Comment by chexburger** [comment]
> The example provided works perfectly fine, are you sure that the bot is running and is in the server?

The help command works just fine. I copied the entire code and pasted my token in making sure it worked. The example worked with help but not with the other commands.

**Comment by truemedian** [comment]
from my knowledge, no examples have a problem with not running the commands. Could you check console for possible errors?

**Comment by chexburger** [comment]
There were no errors in the console.

**Comment by truemedian** [comment]
Has any of the example code been changed from its original state in your testing? If thats the case, could you provide the code with the token stripped out.

**Comment by chexburger** [comment]
It hasn't. I ran it separately to test it.

**Comment by Mishio595** [comment]
The help command example is wrong. If you look at how the command handler works, `args[1]` already contains the prefix, so doing `prefix..args[1]` is simply redundant and breaking.

**Comment by chexburger** [comment]
OHHHHHH. That makes sense. Should've thought of that.

**Comment by truemedian** [comment]
#158 will now fix this error
