### ISSUE TITLE
cannot get attachment URL

### ISSUE THREAD

**Issue by eiiiiix** [SinisterRectus/Discordia#164]
i am creating a logger with this but im unable to log attachment URLs because `message.attachments` doesnt have an option to grab only the url

**Comment by SinisterRectus** [comment]
The `attachments` property is a 1-indexed array of attachments. The `attachment` object is documented [here](https://discordapp.com/developers/docs/resources/channel#attachment-object). You are probably looking for `attachment.url`.

**Comment by eiiiiix** [comment]
ok thanks that worked
my head hurts looking at the stuff i had to do to avoid errors but it works 👍
