### ISSUE TITLE
PrivateChannel.name is potentially misleading

### ISSUE THREAD

**Issue by Mehgugs** [SinisterRectus/Discordia#167]
Channels can have a `name` property sent by discord which is optional as per [docs](https://discordapp.com/developers/docs/resources/channel). DM channels dont get this property, so would it not be better to leave it out since discord documentation says it's optional?

**Comment by SinisterRectus** [comment]
I don't know where the name is listed as optional, it would be helpful if you quoted that section for context.

**Comment by Mishio595** [comment]
https://discordapp.com/developers/docs/resources/channel#channel-object-channel-structure
https://discordapp.com/developers/docs/resources/channel#channel-object-example-dm-channel

**Comment by Mehgugs** [comment]
![the channel structure has it](http://being-gay-is.cool/img/firefox_2019-01-11_15-35-27.png)

[private channel has it's own "name" which implies it's the name discord uses unless you look i the code](https://github.com/SinisterRectus/Discordia/blob/master/libs/containers/PrivateChannel.lua#L27-L29)

**Comment by SinisterRectus** [comment]
The docs that describe it as "Equivalent to PrivateChannel.recipient.username". It's a shortcut. For what reason is this an issue?

**Comment by SinisterRectus** [comment]
- Many Discordia methods and properties do not correlate exactly with the Discord API. This is just one of those instances, and I think that this is not misleading.
- Using the recipient's username as the DM channel's name is not a wild concept, and should have no effect on how Discordia users interact with the Discord API.
- Changing this would be a breaking change, which would require a major version bump.
