### ISSUE TITLE
Provide application object in client

### ISSUE THREAD

**Issue by Mehgugs** [SinisterRectus/Discordia#169]
The [application information](https://discordapp.com/developers/docs/topics/oauth2#get-current-application-information) is useful to have. This is fetched on startup already to grab the owner but would nice to have as a property on the client.

Relevent code at lines [190 - 199](https://github.com/SinisterRectus/Discordia/blob/master/libs/client/Client.lua#L190-L199)
```lua
local app, err3 = api:getCurrentApplicationInformation()
if not app then
	return self:error('Could not get application information: ' .. err3)
end

url = gateway.url
count = gateway.shards
owner = app.owner

cache[user.id] = {owner = owner, shards = count, timestamp = now}
```

**Comment by SinisterRectus** [comment]
42ef61752224c59140b6374bd71cbc3fe53b446e
