### ISSUE TITLE
Issue getting channels

### ISSUE THREAD

**Issue by mistrivious** [SinisterRectus/Discordia#170]
Was playing around with using commands to send messages to other channels. If I use message.channel.send it seems to work, but this only allows you to send a message to the channel the command was sent in. When trying to access a channel through any other means such as guild:getChannel() i get the same error. The code is very simple because i was just testing something out, but i cant get it to work. Im relatively new to this so i cant help but feel like im doing something wrong here, but the error im receiving isnt coming from my own code. Is this a bug?

Code:

```Client:on('messageCreate', function(Message)
if Message.content == BotSettings.Prefix.."test" then
Message:delete()
local Server = Client:getGuild('542884023014522880')
local Channel = Server:getChannel('542884024260100099')
Channel.send("hi")
end
end)```

Error:

deps/discordia/libs/containers/abstract/TextChannel.lua:196: attempt to index field 'client' (a nil value)

**Comment by truemedian** [comment]
This has to due with `send` being a **method** of a TextChannel, meaning it needs to be called using a colon (`:`) instead of like a property.

**Comment by mistrivious** [comment]
ah thanks, feel like an idiot. cant believe i let that one slip.
