### ISSUE TITLE
Sending messages takes ages

### ISSUE THREAD

**Issue by Zurghtapre** [SinisterRectus/Discordia#172]
Hi,

I'm having some trouble with my bot on Linux.

After some minutes without interaction, the bot becomes very slow to send messages.
When I try my !ping command just after bot boot or after it sent another message, it answers quickly, but after a few moments, it can take up to 30 minutes to send.

Here is my log:
```
[Mon 2019-02-18 21:52:30] Zurghtapre (id 191996741719949312) pinging - message id 547158492536897584
[Mon 2019-02-18 21:52:30] Hoji answering - answering user message id 547158492536897584 with command <!ping>
[Mon 2019-02-18 21:52:30] Hoji answered successfully - answering user message id 547158492536897584 with command <!ping>
[Mon 2019-02-18 22:19:24] Zurghtapre (id 191996741719949312) pinging - message id 547165261325664256
[Mon 2019-02-18 22:19:24] Hoji answering - answering user message id 547165261325664256 with command <!ping>
[Mon 2019-02-18 22:35:45] Hoji answered successfully - answering user message id 547165261325664256 with command <!ping>
```

You can see the first ping is answered immediately, while the second one is caught immediately, but takes 15+ minutes to answer back.

It looks like it's better when I run the bot on Windows: I've not seen more than 1 minute to answer back. But I can't be sure.

Is it some config I miss on my Linux or a luvit/Discordia problem?

My Linux is a Raspbian running on Raspberry Pi 3B, I have 500MB RAM free (out of 1 GB), and proc isn't charged at all. Bot is the only running application.

Thanks in advance.

**Comment by SinisterRectus** [comment]
Is your bot running any other code while testing this?

Can you reproduce the issue on more than one network?

**Comment by Zurghtapre** [comment]
My bot isn't running anyhting else.

I can't try for now on another network, I'll try it this week-end if I don't forget.

**Comment by Zurghtapre** [comment]
A little update: with tcptrack, after pinging my bot, I can see a connection to 104.16.59.37:443 (located in the US, I think it's Discord's servers, maybe you can confirm that?), and the idle count goes to around 40 seconds then resets back to 0 s. I'm not sure I can wait for the !pong to be successfully sent to confirm, but it looks like I go to the server timeout several times before my message is accepted.

**Comment by Zurghtapre** [comment]
Ok, so I just tried with my phone connection in Wifi, and it works great even after 30 minutes.

I switched back to my box, both Ethernet and Wifi have the latency.
Do you know a fix for that?

**Comment by SinisterRectus** [comment]
Sounds like an RPI issue? I've never used one, so I don't know what to do.

**Comment by Zurghtapre** [comment]
I'd say it looks more like an Internet box issue.
Thanks anyway, I'll continue searching a fix and will post it if I find a solution.

**Comment by Zurghtapre** [comment]
Well, I put my box on bridge only mode, and I'm now using a Netgear router as the actual router, and it works well.

I think we can close that issue, and say that my internet provider's box is bad XD
