### ISSUE TITLE
[Voice] Performance issue 

### ISSUE THREAD

**Issue by LaevusDexter** [SinisterRectus/Discordia#173]
Considering: http://luajit.org/ext_ffi_api.html ("Creating cdata Objects" paragraph)

https://github.com/SinisterRectus/Discordia/blob/7bd919a476c6f0eb223c406549ba6f517c44585f/libs/voice/sodium.lua#L62
and
https://github.com/SinisterRectus/Discordia/blob/7bd919a476c6f0eb223c406549ba6f517c44585f/libs/voice/sodium.lua#L75
and
https://github.com/SinisterRectus/Discordia/blob/4d4a8bb22d64dd2884a237b56281c7138e38dbf3/libs/voice/opus.lua#L219
and
https://github.com/SinisterRectus/Discordia/blob/4d4a8bb22d64dd2884a237b56281c7138e38dbf3/libs/voice/opus.lua#L179
and 
https://github.com/SinisterRectus/Discordia/blob/4d4a8bb22d64dd2884a237b56281c7138e38dbf3/libs/voice/opus.lua#L180

Are slower (especially in voice sending loop)  than using factory that returns from ffi.typeof.

Solution:
```lua
  local new_uchar_array = ffi.typeof('unsigned char[?]')
...

local encrypted = new_uchar_array(encrypted_len)
```

Also, afaik, jit ffi works faster with native namespaces, than by caching it in local variable(except ffi.C)

**Comment by Mehgugs** [comment]
This is the correct use of ffi.new since the lengths are the not constant. I'm not sure how this changes memory behaviour when both ffi.new and typeof constructors return garbage collected objects.

**Comment by LaevusDexter** [comment]
This's not:

> Please note that an anonymous struct declaration implicitly creates a new and distinguished ctype every time you use it for ffi.new(). This is probably not what you want, especially if you create more than one cdata object. Different anonymous structs are not considered assignment-compatible by the C standard, even though they may have the same fields! Also, they are considered different types by the JIT-compiler, which may cause an excessive number of traces. It's strongly suggested to either declare a named struct or typedef with ffi.cdef() or to create a single ctype object for an anonymous struct with ffi.typeof().

ffi.new creates new ctype and initialize it. 
ffi.typeof creates only ctype and returns factory for this ctype.

There may exist more than one same ctype, so it may be called as leak.

In other words, every call of ffi.new creates new non garbage collected ctype.
Lengths are one of argument of array factory.

**Comment by Mehgugs** [comment]
That section is talking about an anonymous struct type only, and not all objects created from ffi.new .

**Comment by LaevusDexter** [comment]
Oh, yes, my rapidly reading fault, that's may be not leak, so that's doesn't override text above of last quote to be sure:

> Performance notice: if you want to create many objects of one kind, parse the cdecl only once and get its ctype with ffi.typeof(). Then use the ctype as a constructor repeatedly.

So, since such functions calls in loop, performance are comes first, isn't?
As I said, factory that returns from ffi.typeof takes same arguments except type, no requires to use ffi.new.

**Comment by SinisterRectus** [comment]
I wasn't aware that you can use ctype constructors with VLAs. I'll look into changing it, but I don't expect a huge performance increase. Encrypting is fast; encoding is the bottleneck.
