### ISSUE TITLE
Attempt to index global 'guild' (a nil value)

### ISSUE THREAD

**Issue by semiboop** [SinisterRectus/Discordia#176]
I am trying to make a feature where when a specific command is used, it puts an output into the console where it states the command used, who used it, and what guild it was used in. But when I try to use "guild.name"  it gives me "attempt to index global 'guild' (a nil value)". I've tried my hardest to find a solution to this but I can't.
I am new to programming lua so bare with me.

Here is the code for that portion:

client:on('messageCreate', function(message)
	if message.content == ('/gayman quote') then
		print('quote command used' .. guild.name 'by' .. user.username)
	end
end)

Thanks!

**Comment by Mishio595** [comment]
Show where you define `guild`. I see it nowhere in that code snippet and would expect guild to be nil in this context.

**Comment by semiboop** [comment]
> Show where you define `guild`. I see it nowhere in that code snippet and would expect guild to be nil in this context.

I have no clue how to define guild.

**Comment by Mishio595** [comment]
Here are some resources for learning Lua so you can better understand how to define variables. I highly recommend undertaking some more basic projects before building a Discord Bot as they tend to become quite complicated.

- https://www.lua.org/manual/5.1/index.html
- https://www.lua.org/pil/contents.html
- http://lua-users.org/wiki/TutorialDirectory
- http://thomaslauer.com/download/luarefv51.pdf

**Comment by semiboop** [comment]
Thank you, but I still would like an answer to this. I am not new to programming, but just new to Lua.
Thanks!

**Comment by Mishio595** [comment]
The error said everything there is to say. `guild` is a nil value, meaning it was never defined or was assigned nil. You never defined guild, so it is nil.

That being said, you are likely wanting the guild the message was sent in based on the code you provided. You have a message object in scope, assigned to `message`, and for messages sent in a guild, `message.guild` is defined. Keep in mind that `message.guild` will be nil if the message was sent in a private channel. For more information on the Message class, you can find the documentation [in the wiki](https://github.com/SinisterRectus/Discordia/wiki/Message).

**Comment by semiboop** [comment]
Thanks! But now I've gotten a completely new error.
It says: 

_attempt to concatenate field 'guild' (a table value)_

**Comment by Mishio595** [comment]
Objects are tables. you cannot concatenate tables. This is another basic Lua error and once again I will refer you to the tutorials I linked earlier. We are not here to fix basic errors which can be easily resolved with some reading.

**Comment by semiboop** [comment]
Alright so, I think I did something right. I am no longer getting any errors. But when I do said command, I am not getting an output in console. It is locally defined.

Here is my code for this area now:
```
client:on('messageCreate', function(message)
local message = "message.name"
	if message.content == ('/gayman') then
		print('/gayman command used on by ' .. message.name)
	end
end)
```

**Comment by SinisterRectus** [comment]
You are overwriting the message object with a string and then you are indexing that string with a key. This is valid Lua, but it will not get you any closer to what you are trying to do.

Please take some time to look at your code and think critically about what the code is doing versus what you want it to do.

**Comment by semiboop** [comment]
Well, thanks for trying to help me. I honestly have no clue what to do. I'm just tired right now and can't think right. I gotta sleep.

This is what I've left off with.
Let me know what I'm doing wrong and what needs to be re-coded.
Sorry yet again if this isn't the right area to ask for this kind of help.
But thanks!
```
client:on('messageCreate', function(message)
local message_user = message.author
	if message.content == ('/gayman') then
		print('gayman command used by' .. message_user)
	end
end)
```

**Comment by Xh4H** [comment]
This is not an issue made by this Library. Come to our Discord channel and ask there.

**Comment by semiboop** [comment]
Okay. Where can I get the link to the Discord server? And do I need to close this issue?

**Comment by Infinixius** [comment]
https://discord.gg/discord-api

If your question has been answered, or your going to ask in DAPI, yes, you can probably close this issue.

**Comment by tigerism** [comment]
Can this be closed
