### ISSUE TITLE
[ERROR] 403 - FORBIDDEN problem

### ISSUE THREAD

**Issue by ChonkinTenders** [SinisterRectus/Discordia#177]
Basically I'm trying to add a role with the command of !apply. I'm pretty sure my syntax is right because iv'e gotten rid of a lot of different errors. My bot also has a role with the Administrator perm. Here's my code:

client:on('messageCreate', function(message)
	
	if message.author == client.user then return 0 end

	if message.content == '!apply' then
		local succ,err = pcall(function()
			--print(message.user:hasRole(goodBoiRoleID))
			message.member:addRole(goodBoiRoleID)
		end)
		if succ then
			message.channel:send('Alright, here is your **good boi certification** role **'..message.author.username..'**')
		else
			message.channel:send('There was a problem adding your role, **'..message.author.username..'**')
			print('Problem adding role to '..message.author.username..'. '..err)
		end
	end
end)

It doesn't print that there's a problem anymore but now I get the following error: 2019-03-13 13:07:12 | [ERROR]   | 403 - FORBIDDEN : PUT https://discordapp.com/api/v7/guilds/555199243485184024/members/410111287872323594/roles/555371489252212791.
The role ID is definitely right and I have no idea what the problem is. PLEASE HELP!!!

**Comment by Mehgugs** [comment]
Can you post the value of `err`

**Comment by Bilal2453** [comment]
Are you sure that you were created that Role ?
So is that role in the same guild.

**Comment by ChonkinTenders** [comment]
> Are you sure that you created that Role ?
> So is that role in the same guild.

How do I know the role is in the same guild? I made a test server to test the bot in.

**Comment by ChonkinTenders** [comment]
> Can you post the value of err
> EDIT:
> local succ,err = message.member:addRole(goodBoiRoleID)
> use this instead of the pcall.

How do I find the value of err

**Comment by SinisterRectus** [comment]
From here on out, I'm going to start discouraging people from using GitHub issues to ask coding questions. Please visit the #lua_discordia channel at https://discord.gg/discord-api instead.
