### ISSUE TITLE
400 - BAD REQUEST

### ISSUE THREAD

**Issue by antiafk** [SinisterRectus/Discordia#178]
I do not know if this is really an API error, but I already report it by prevention.

I was testing my BOT, and when I said such a command to it, it just does not execute the command (display a message on the channel), and there is an error in the console that would be this:

![badrequest](https://user-images.githubusercontent.com/42821200/54378627-74b2e380-4666-11e9-877c-fd5b5de7d2cf.PNG)

**Comment by Jabbers99** [comment]
Firstly, we need more info such as your code to help you.
Secondly, if you seem uncertain if this is a library error, it is strongly discouraged and to ask coding questions here, please ask in the #lua_discordia channel in https://discord.gg/discord-api.

**Comment by antiafk** [comment]
> Firstly, we need more info such as your code to help you.
> Secondly, if you seem uncertain if this is a library error, it is strongly discouraged to ask coding questions here, please ask in the #lua_discordia channel in https://discord.gg/discord-api.

Ah, ya, the code...

```Lua
if content == prefix .. "help" then
	local file = io.open("archives/help.txt", "r")
	message:reply(file:read("*a"))
	file:close()
end
```
