### ISSUE TITLE
messageUpdate/Delete spams the message in logger

### ISSUE THREAD

**Issue by eiiiiix** [SinisterRectus/Discordia#179]
whenever a message is deleted or edited the message gets spammed in my logger
![image](https://user-images.githubusercontent.com/30561378/55450263-7b030280-5609-11e9-9f17-6607215a7626.png)
![image](https://user-images.githubusercontent.com/30561378/55450310-a259cf80-5609-11e9-88c1-fb775dbfaa0f.png)

this is the code:
`sl_t(0.1)` is a 100ms sleep timer i made so it wouldnt see every message since boot as deleted
```lua
--other functions
local clock = os.clock
function sl_t(n) --like wait in bB
	local t0 = clock()
	while clock() - t0 <= n do
	end
end
--other functions
local parsemsg = function(message)

print('Reading new messages at ', sw.milliseconds, ' milliseconds')
local sw2 = discordia.Stopwatch()
--other logger stuff
	client:on('messageUpdate', function(message)
		print('LOG-EDT:  ', message.author.tag, message.content)
		c81e728d9d4c2f636f067f89cc14862c = io.open('./logs/' .. message.channel.id .. '_all.txt', 'a+')
			if not (c81e728d9d4c2f636f067f89cc14862c) then
--copy commands for the differenet OSs, nothing interesting since most are linux based
				c81e728d9d4c2f636f067f89cc14862c = io.open('./logs/' .. message.channel.id .. '_all.txt', 'a+')
			end
		c81e728d9d4c2f636f067f89cc14862c:write('LOG-EDIT: ', message.timestamp, ' ', '<#', message.channel.id, '>', ' ', message.author.tag, ":", '<@!', message.author.id, '>', ' ', message.id, ': ', '\n', 'MESSAGE: ', message.content, '\n', message.link)
			if (message.attachment) then
				c81e728d9d4c2f636f067f89cc14862c:write('\n', message.attachment.url)
			end
		c81e728d9d4c2f636f067f89cc14862c:write('\n\n')
		c81e728d9d4c2f636f067f89cc14862c:close()
	sl_t(0.1)
	end)
--commands
end
--error reporting and token
```
it happens for bothe messageUpdate and messageDelete with this and is 10x worse without my timer...
![image](https://user-images.githubusercontent.com/30561378/55451084-696f2a00-560c-11e9-9c59-eaf337f898f0.png)
the md5 hashes are just so i never have interfering globals on accident 
any help with this would be nice
currently edits deletes and embeds are the only things my bot doesnt log

**Comment by Mishio595** [comment]
You're registering a listener everytime you call parsemsg, hence the spam. Each listener is executed when the event is emitted. Also, your timer is blocking, not sure if thats intentional or not.

**Comment by eiiiiix** [comment]
the blocking was intentional
but doing the edit/delete any other way makes almost every message register as edited
![image](https://user-images.githubusercontent.com/30561378/55451731-29f60d00-560f-11e9-94fe-2ebbe25a075e.png)

**Comment by Mishio595** [comment]
`client:on("event", callback)` calls `callback` every time `"event"` is fired from the client. `"messageUpdate"` is fired everytime any message is edited. I'm not sure what you're trying to accomplish.

**Comment by eiiiiix** [comment]
ok i found a way to fix it
```lua
client:on('messageUpdate', function(message)
	if (message.oldContent) then
		local oldmessagetable = tbld(message.oldContent)
		print('LOG-EDT:  ', message.author.tag, oldmessagetable, '>', message.content)
				c81e728d9d4c2f636f067f89cc14862c = io.open('./logs/' .. message.channel.id .. '_all.txt', 'a+')
			if not (c81e728d9d4c2f636f067f89cc14862c) then
--os stuff
				c81e728d9d4c2f636f067f89cc14862c = io.open('./logs/' .. message.channel.id .. '_all.txt', 'a+')
			end
		c81e728d9d4c2f636f067f89cc14862c:write('LOG-EDIT: ', message.timestamp, ' ', '<#', message.channel.id, '>', ' ', message.author.tag, ":", '<@!', message.author.id, '>', ' ', message.id, ': ', '\n', 'OLD-MESSAGE:', oldmessagetable, '\n\nNEW-MESSAGE: ', message.content, '\n', message.link)
			if (message.attachment) then
				c81e728d9d4c2f636f067f89cc14862c:write('\n', message.attachment.url)
			end
		c81e728d9d4c2f636f067f89cc14862c:write('\n\n')
		c81e728d9d4c2f636f067f89cc14862c:close()
	end
end)
```
it checks if there was old content
and `tbld` just converts a table to a string
