### ISSUE TITLE
Issue while trying to os.execute().

### ISSUE THREAD

**Issue by Martian24** [SinisterRectus/Discordia#180]
Alright so, i wanted to make something like CMD inside my bot.
But, everytime i do !ping google.com, it pings in the CMD but, when it should to reply the message result of the ping, it gives me 400 BAD REQUEST ERROR. It might be over 2000 char. but somehow it doesn't have more than 2000 char.

https://gyazo.com/dbfed202e21204fbab40fd020e490f70

**Comment by Martian24** [comment]
Even when i do simple echo 'hi' it gives me error.

**Comment by tigerism** [comment]
This means you're supplying bad message data to Discord. An example could be over 2k characters (as you said), an embed with a field value of nil, or any other bad data.

Debug your code.

**Comment by truemedian** [comment]
Discord also gives helpful errors with bad requests, you can access it as the second return from :send() like `local msg, err = channel:send(....)`

**Comment by Martian24** [comment]
Yes but echo 'hi' has only 2 chars, and it still gives me an error.

**Comment by tigerism** [comment]
Debug your code. 

Does it work with a static value? e.g. channel:send("test")
Does it error as soon as you place the variable in? If so, print your variable and debug it from there.

**Comment by SinisterRectus** [comment]
This does not appear to be a library issue. If you need support with using the library, you should visit our channel at https://discord.gg/discord-api.

**Comment by eiiiiix** [comment]
does the command have a string splitter in it? it could just be sending the entire message
i was having similar issues until i made it [split the string](https://stackoverflow.com/a/7615129)

**Comment by SinisterRectus** [comment]
Closing because stale. Use our Discord channel for further support.
