### ISSUE TITLE
Could not authenticate

### ISSUE THREAD

**Issue by Woody3534** [SinisterRectus/Discordia#181]
C:\Users\Biostar\Desktop\discordia>luvit bot.lua
2019-04-06 22:58:38 | [INFO]    | Discordia 2.6.0
2019-04-06 22:58:38 | [INFO]    | Connecting to Discord...
2019-04-06 22:58:38 | [ERROR]   | Could not authenticate, check token: ...Biostar/Desktop/discordia/deps/secure-socket/context.lua:53: bad argument #1 to 'ctx_new' (only support TLS, DTLS to negotiate highest available SSL/TLS or DTLS version above openssl v1.1.0
optional followed by _client or _server
default is TLS
)

This might be me being dumb, but i dont think its related to me o.o

**Comment by SinisterRectus** [comment]
Might be this issue? luvit/lit#256. Try removing your secure-socket folder and install a fresh copy. This may be fixed with version 1.2.2.

**Comment by Woody3534** [comment]
I deleted the whole folder, installed everything again, and now that error is gone theres a new one
2019-04-07 00:04:49 | [ERROR]   | 401 - UNAUTHORIZED : GET https://discordapp.com/api/v7/users/@me
2019-04-07 00:04:49 | [ERROR]   | Could not authenticate, check token: HTTP Error 0 : 401: Unauthorized
im pretty sure the token is right, and im using > 
client:run("Bot "..token)

**Comment by SinisterRectus** [comment]
I'm not sure what else can cause this. Have you tried connecting with a different token from either the same account or a different account? Have you tried connecting from a different location?

**Comment by TradeabIe** [comment]
The same problem for me, I tried with multiple tokens and it still failed. Not sure what's causing this.

**Comment by SinisterRectus** [comment]
If you are sure that you are correctly using the token, then maybe your IP address is banned.

**Comment by TradeabIe** [comment]
This is my first time ever using discordia

**Comment by SinisterRectus** [comment]
Then I suspect that you aren't properly using the token. Join our server for further support. https://discord.gg/discord-api

**Comment by TradeabIe** [comment]
I am in there. I am using the right token, and I know it because I have another bot made in discord.js and I know where and how to put the token. I used the format for putting the token and it didn't work. I'm in there though if you want to chat.

**Comment by Woody3534** [comment]
I made 3 bots on 3 random discord accounts on 3 random ip adresses, and none work.
I even tried using node.js instead of lua and i get the 
UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
So it might be a discord bug or i dont even know...

**Comment by TradeabIe** [comment]
node.js and discord.js work perfectly for me. In fact, I just change my token for my bot 30-40 minutes ago and no error.

**Comment by SinisterRectus** [comment]
You will have to inspect the raw request body to confirm that the token is being sent in the headers properly. I'm not able to help with this at the moment.

**Comment by dawglazvari** [comment]
Try authenticating with a token publicly available, 
**MjM4NDk0NzU2NTIxMzc3Nzky.CunGFQ.wUILz7z6HoJzVeq6pyHPmVgQgV4**
running _?tag a real token_ shows this token fyi

**Comment by Woody3534** [comment]
reinstalled the whole thing again, works perfectly fine. thanks for the help i guess
