### ISSUE TITLE
"Could not authenticate, check token:"

### ISSUE THREAD

**Issue by ShiforGitHub222** [SinisterRectus/Discordia#182]
Could not authenticate, check token: ...ents/Discord Bots/EuroBot/deps/secure-socket/context.lua:67: #1:TLS not supported
Maybe [SSLv3] SSLv23 TLSv1 TLSv1_1 TLSv1_2 DTLSv1 [SSLv2], option followed by _client or _server

Tried a full reinstall, nothing works. I'm definitely entering the token correctly.

local token = "my token is here but obviously i dont want to reveal it"
client:run("Bot "..token)

**Comment by SinisterRectus** [comment]
What version of secure-socket do you have? Run `lit ls`

**Comment by ShiforGitHub222** [comment]
I tried that, it still outputs the same error.

**Comment by ShiforGitHub222** [comment]
Fixed it:
Instead of using get-lit v0.2 I used the v0.1 version and it worked.

**Comment by SinisterRectus** [comment]
Ah. I didn't realize that was an issue. I will update my get-lit app to support the latest binaries. I recommend that people use the official installation script(s) at https://luvit.io/install.html, since my get-lit app is supposed to be somewhat of a backup option.

**Comment by SinisterRectus** [comment]
I decided to delete my `get-lit` app. It really was supposed to be a temporary work around anyway.
