### ISSUE TITLE
Suggestion & Issue

### ISSUE THREAD

**Issue by CleverSource** [SinisterRectus/Discordia#187]
It isn't completely an issue but it is very hard to make a modular project with this, I had to pass around my required version of Discordia from my main script through every module. It looked something like this:
```lua
-- Not exact as I wrote this on Github. No clue if this would even work, but it's an example.
local Discordia = require("discordia")
local SomeModule = require("moduleFolder/someModule")

SomeModule:Run("params", {
    -- Passed modules.
    ["Discordia"] = Discordia
})
```

I would prefer to be able to require Discordia from any script but due to Luvit you can only do it from the main script, please correct me if I'm incorrect about this!

Now my suggestion is adding database options, I couldn't find a any redis and/or mongo options for lua. I would really love a built-in rethinkdb, redis, and mongo lua library into this project. It would definitely help with productivity. I do understand lua obviously isn't ideal for a Discord bot but I could see lua being very promising to make a Discord bot with as it's very quick and to the point. I also would love to see a built-in wait(num) which pauses the thread for that amount of time, but it only pauses the scope, so if you use it in a function then it pauses the function from running for x seconds but nothing else. Example of this below:
```lua
function a(b)
       print(b)
       wait(5)
       b = b + 5
       print(b)
end

a(9)
print("hi") -- still runs while wait in function happens
```

**Comment by truemedian** [comment]
Due to how luvit works off of lua, its require is different than the standard lua one, which it will fall back to if it cant find the file you're looking for. When it falls back to said normal lua require, the luvit require (which looks for deps/ and etc.) will not be used in those required files.

What you need to do is tell luvit's require, hey, im looking for a file right here where im working. Such that `moduleFolder/someModule` becomes `./moduleFolder/someModule.lua`

**Comment by SinisterRectus** [comment]
Were you able to resolve this?

**Comment by CleverSource** [comment]
Yes, but I still do have a suggestion apart of this.

**Comment by SinisterRectus** [comment]
Luvit has a `timer` module, and that module has a `sleep` function. It pauses a coroutine for a specified number of milliseconds.

**Comment by SinisterRectus** [comment]
I will not be including any database libraries as a part of Discordia, unless for some reason Discordia needs one to operate. There is no reason to encourage or enforce the use of one database over another, as they all serve slightly different purposes, and people have their own opinions about which ones to use.

Lit should make it easy enough to install any libraries that exist.

I don't expect any database libraries to be built into Luvit or Luvi for the same reason, and there would be extra work involved for their maintainance. Here is an example of SQLite being rejected from inclusion in Luvi: luvit/luvi#44.

Even something small and popular like SQLite was rejected at luvit/luvi#44
