### ISSUE TITLE
How do I display image in embed?

### ISSUE THREAD

**Issue by DV69GT** [SinisterRectus/Discordia#189]
I want to put a image in embed using a link, please help.
thanks

**Comment by Jabbers99** [comment]
Hey.
You would want to use the `image` field of the embed.
A basic example:
`message.channel:send {
  embed = {
    title = "This is an embed!",
    image = {
          url = myUrlHere
    },
    color = discordia.Color.fromRGB(114, 137, 218).value,
    timestamp = discordia.Date():toISO('T', 'Z')
  }
}`
You can read more about this [here](https://discordapp.com/developers/docs/resources/channel#embed-object-embed-image-structurel).

Also, for a quicker response time you can always ask in our channel in the Discord API discord (#lua-discordia).
https://discord.gg/discord-api

**Comment by DV69GT** [comment]
@Jabbers99 Thank you so much!!!!!
