### ISSUE TITLE
unhandled gateway event on channel mute

### ISSUE THREAD

**Issue by eiiiiix** [SinisterRectus/Discordia#190]
when run on a user account and a channel gets muted by the user a unhandled gateway event (USER_GUILD_SETTINGS_UPDATE)

![image](https://user-images.githubusercontent.com/30561378/58389077-cc6db380-7ff4-11e9-849d-e5b7beb80043.png)

**Comment by SinisterRectus** [comment]
I've added this to the list of ignored events. I will not be adding a handler for it, as running user accounts is no longer supported. 133de9d85914172802503fdedb3974deb2fded3d
