### ISSUE TITLE
Help with SQLite.

### ISSUE THREAD

**Issue by Martian24** [SinisterRectus/Discordia#193]
Title says all.
![image](https://user-images.githubusercontent.com/49285034/58990715-3f460e00-87ef-11e9-93a4-167a673d5ebf.png)

**Comment by Martian24** [comment]
It's VPS. Linux.

**Comment by SinisterRectus** [comment]
This is not an appropriate location to receive SQLite help. You also haven't shown any code that may be related to the issue.

**Comment by Martian24** [comment]
It's the sqlite library which you have on github. The code error is inside the sqlite3.lua

**Comment by SinisterRectus** [comment]
Then open an issue at that repository, and please include your code that opens a database. 

https://github.com/SinisterRectus/lit-sqlite3
