### ISSUE TITLE
Could Not Authenticate 

### ISSUE THREAD

**Issue by caleb123neal** [SinisterRectus/Discordia#194]
![image](https://user-images.githubusercontent.com/20615679/59136530-281b3380-8949-11e9-939a-80abd164b5c1.png)

keep getting this error when attempting to start my bot

**Comment by Mishio595** [comment]
Reinstall discordia and its dependencies, this error happens when your coro-* deps are out of date. Lit will not fetch new files if any version is found, so you have to delete the `deps` directory.

**Comment by caleb123neal** [comment]
Nope, didn't work (I'm running it in docker if that helps)

**Comment by caleb123neal** [comment]
Managed to get it working, here's the package I ended up using for those with the same issue - 
`return {
  name = "caleb/discordbot",
  version = "0.2.0",
  private = true,
  dependencies = {
'creationix/coro-http@3.0.0',
    'creationix/coro-websocket@3.1.0',
    'luvit/secure-socket@1.2.0',
    "creationix/coro-wrapper",
    "luvit/luvit",
     "SinisterRectus/discordia@2.6.0"
  },
  description = "A bot for discord",
}
`
