### ISSUE TITLE
Add cleanup functionality to Emitter

### ISSUE THREAD

**Issue by JohnnyMorganz** [SinisterRectus/Discordia#196]
Currently, for the EventEmitter utility in Discordia, you can only remove all listeners by a given named event.

There should be a method to clear up all listeners that are currently subscribed, regardless of the name of the event, eg via a method like `Emitter:cleanup()` or `Emitter:destroy()`

This would be useful when you no longer require the Emitter anymore, as currently the alternative is to call `Emitter:removeAllListeners()` on any available name that could be used. I currently have a situation where I have a class which extends the Emitter, and when an object is no longer required, there is no simple way to clean up all the listeners connected to it

**Comment by SinisterRectus** [comment]
Do you think it would be a good idea to implement `Emitter:removeAllListeners()` so that it literally removes all listeners when no `name` argument is passed?

**Comment by JohnnyMorganz** [comment]
It makes sense in this instance to do so, as that is all that is happening
