### ISSUE TITLE
Is there a way to use webhooks without registering a bot?

### ISSUE THREAD

**Issue by BestMordaEver** [SinisterRectus/Discordia#199]
I don't really see any ways to interact with webhooks in this library other than create and manage them. Do I even need it to use webhooks?

**Comment by SinisterRectus** [comment]
No. Once you have the webhook ID and token, you can use any HTTP client to post webhook messages. There are some conveniences in Discordia like file uploading or mention parsing, but I have written any code to connect these to webhooks; Discordia is entirely a bot library.

**Comment by BestMordaEver** [comment]
Shame. Still gonna use it for a bot tho!
