### ISSUE TITLE
Client continues receiving events after logout is called

### ISSUE THREAD

**Issue by Dummiesman** [SinisterRectus/Discordia#2]
After calling logout, and seeing the endpoint called in console, the client continues to receive events as if it was logged in.

**Comment by SinisterRectus** [comment]
The logout method is left over from a earlier version, one without WebSocket support. I'll need to implement WebSocket closing and maybe connection states (logged in, logged out, disconnected)  to fix this.

**Comment by SinisterRectus** [comment]
Fixed with 607c9a03322fba0ef8bab441970899bcb213f697. Use `Client:stop()` to fully terminate a running client.
