### ISSUE TITLE
Field "name" in Channel class

### ISSUE THREAD

**Issue by BestMordaEver** [SinisterRectus/Discordia#201]
There is no reference about field "name" of class Channel in wiki, which really confused me. TextChannel and VoiceChannel also don't reference this. Please, add it.

**Comment by SinisterRectus** [comment]
These classes don't have a name property to document.

**Comment by BestMordaEver** [comment]
Yet this code works
`print(message.channel.name)`

**Comment by SinisterRectus** [comment]
Presumably because that is a GuildTextChannel, which has a name property implemented by the GuildChannel class. This is documented.

**Comment by BestMordaEver** [comment]
Oh ok, that explains a lot. It's just that in Message doc there was no mention of GuildChannel and I didn't look it up myself. Thanks!

**Comment by SinisterRectus** [comment]
True. It is documented as TextChannel, but this is an abstract class, so the actual class is something that implements TextChannel. I will think of a way to make this clearer.

**Comment by SinisterRectus** [comment]
This is now fixed with 483e23c1ba62e99ad07cf63fd950dc3e26f06f56. See the updated class documentation at https://github.com/SinisterRectus/Discordia/wiki#class-api.
