### ISSUE TITLE
How does bot manage permissions?

### ISSUE THREAD

**Issue by BestMordaEver** [SinisterRectus/Discordia#205]
My bot needs to assign users certain channel-specific permissions. I don't see how to even get the channel-specific permissions in the first place. Is it something bots can manage?

**Comment by SinisterRectus** [comment]
The easiest way is to use the [`Member:hasPermission`](https://github.com/SinisterRectus/Discordia/wiki/Member#haspermissionchannel-perm). For example:
```lua
if guild.me:hasPermission(channel, "sendMessages")` then
  channel:send("hello")
end
```
See the [enumerations ](https://github.com/SinisterRectus/Discordia/wiki/Enumerations#permission)page for available permission values.

These issues are not really meant for coding support. If you want more help with this, you should visit our channel at https://discord.gg/discord-api.
