### ISSUE TITLE
I can't find the event to check a role

### ISSUE THREAD

**Issue by lollocipox** [SinisterRectus/Discordia#207]
I'm trying to control an event where a user adds a role to another user, when that happens the bot starts up.

**Comment by truemedian** [comment]
Sorry for the very late response but the event you are looking for is called `memberUpdate` which is emitted when any property of that member such as roles or their nickname change. You can find it [here](https://github.com/SinisterRectus/Discordia/wiki/Events#memberupdate). There is no specific event for when a role is added, nor will it tell you who added the role, to get who performed the action you will have to query the audit logs.

**Comment by SinisterRectus** [comment]
I'll assume this is resolved. Either way, please visit our channel at https://discord.gg/discord-api for further support.
