### ISSUE TITLE
How do I make my bot chat in a specific textchannel inside my server?

### ISSUE THREAD

**Issue by CrazyFlankz** [SinisterRectus/Discordia#210]
I have a command that will DM someone a message when you mention them (?dm @ mention text). I have it set up where whenever the bot receives a pm, it prints the user's username along with the pm the bot received. I've decided to upgrade this so it sends these logs to a specific channel inside my discord. I've been trying for so long and I just can't get it right.

I've tried using client:getChannel(id) but no luck!

**Comment by SinisterRectus** [comment]
For support with using the library, visit our channel at https://discord.gg/discord-api.
