### ISSUE TITLE
Attempt to index field 'client' a nil value

### ISSUE THREAD

**Issue by TripTripy** [SinisterRectus/Discordia#213]
When I try and run this piece of code by putting in the respective command on discord
`if command == "timeconverter" then
		if isnum(string.sub(args[4], 1, 2)) ~= true then local invalid = true message.channel:send("Time \"" .. args[4] .. "\" is not valid") end
		if isnum(string.sub(args[4], 4, 5)) ~= true then local invalid = true message.channel:send("Time \"" .. args[4] .. "\" is not valid") end
		if tonumber(string.sub(args[4], 1, 2)) >12 or tonumber(string.sub(args[4], 1, 2))<1 then local invalid = true message.channel:send("Time \"" .. args[4] .. "\" is not within the constraits of time") end
		if string.sub(args[4], 3, 3) ~= ":" then local invalid = true message.channel:send("Time \"" .. args[4] .. "\" is not valid") end
		if string.sub(args[2], 1, 4) ~= "UST-" or "UST+" or "GMT-" or "GMT+" then local invalid = true message.channel.send("Timezone \"" .. args[2] .. "\" Is Not Valid") end
		if string.sub(args[3], 1, 2) ~= "AM" or "PM" then local invalid = true message.channel:send("AM/PM is not valid") end
		if args[5] == "DST" then local daylightsavings = true else daylightsavings = false end
		if invalid ~= true then
		local varhour = string.sub(args[4], 1, 2)
		local varsec = string.sub(args[4], 4, 5)
		local offsetpt1 = tonumber(string.sub(args[2], 5, 6))
		if string.sub(args[3], 1, 2) == "AM" then ampm = "AM" else ampm = "PM" end
		if string.sub(args[2], 4, 4) == "+" then
			local offset = offsetpt1
		
		else local offset = ("-" .. offsetpt1) end
		function getTime(neededoffset, offset2)
			local neededtimept1 = neededoffset-offset2
			local newhourpt1 = neededtimept1+varhour
			if newhourpt1>12 then newhourpt1 = newhourpt1-12 
				if ampm == "AM" then ampm = "PM" 
				else ampm = "AM" end
			end
			if newhourpt1<0 then newhourpt1 = newhourpt1+12 
				if ampm == "AM" then ampm = "PM" 
				else ampm = "AM" end
			end
			if newhourpt1==12 then
				if neededtimept1 < 0 then if ampm == "AM" then ampm = "AM" else ampm = "PM" end end
				if neededtimept1 > 0 then if ampm == "AM" then ampm = "PM" else ampm = "AM" end end
			end
			return (newhourpt1 .. ampm)
			end
			message.channel:send("GMT/UTC -12 : " .. getTime(-12, offset))
			message.channel:send("GMT/UTC -11 : " .. getTime(-11, offset))
			message.channel:send("GMT/UTC -10 : " .. getTime(-10, offset))
			message.channel:send("GMT/UTC -9  : " .. getTime(-9, offset))
			message.channel:send("GMT/UTC -8  : " .. getTime(-8, offset))
			message.channel:send("GMT/UTC -7  : " .. getTime(-7, offset))
			message.channel:send("GMT/UTC -6  : " .. getTime(-6, offset))
			message.channel:send("GMT/UTC -5  : " .. getTime(-5, offset))
			message.channel:send("GMT/UTC -4  : " .. getTime(-4, offset))
			message.channel:send("GMT/UTC -3  : " .. getTime(-3, offset))
			message.channel:send("GMT/UTC -2  : " .. getTime(-2, offset))
			message.channel:send("GMT/UTC -1  : " .. getTime(-1, offset))
			message.channel:send("GMT/UTC  0  : " .. getTime(0, offset))
			message.channel:send("GMT/UTC +1  : " .. getTime(1, offset))
			message.channel:send("GMT/UTC +2  : " .. getTime(2, offset))
			message.channel:send("GMT/UTC +3  : " .. getTime(3, offset))
			message.channel:send("GMT/UTC +4  : " .. getTime(4, offset))
			message.channel:send("GMT/UTC +5  : " .. getTime(5, offset))
			message.channel:send("GMT/UTC +6  : " .. getTime(6, offset))
			message.channel:send("GMT/UTC +7  : " .. getTime(7, offset))
			message.channel:send("GMT/UTC +8  : " .. getTime(8, offset))
			message.channel:send("GMT/UTC +9  : " .. getTime(9, offset))
			message.channel:send("GMT/UTC +10  : " .. getTime(10, offset))
			message.channel:send("GMT/UTC +11  : " .. getTime(11, offset))
			message.channel:send("GMT/UTC +12  : " .. getTime(12, offset))
		
		end
	end`
i get this as an error
`Uncaught Error: ...ents/DiscordBot/discordbot rewrite/deps/coro-channel.lua:62: ...discordbot rewrite/deps/discordia/libs/utils/Emitter.lua:103: .../deps/discordia/libs/containers/abstract/TextChannel.lua:279: attempt to index field 'client' (a nil value)`
Is this a me error or discordia error? If its me what did i do wrong?

**Comment by SinisterRectus** [comment]
You need to call the method `message.channel:send()` instead of `message.channel.send()`.

**Comment by TripTripy** [comment]
Thank you! Not sure how i missed that
