### ISSUE TITLE
Tagging Users.

### ISSUE THREAD

**Issue by TripTripy** [SinisterRectus/Discordia#215]
How could I go about tagging users in a message? I've tried doing
`message.channel:send("@" .. user.tag` with user being either the message author or a ping in the authors message. This just sends plain text however. What would be the right way to do it?

**Comment by truemedian** [comment]
both the User and Member classes have a `mentionString` property which will give you a string with the mention format discord requires (`<@id>`)

**Comment by TripTripy** [comment]
Thank You!
