### ISSUE TITLE
var defined is nil

### ISSUE THREAD

**Issue by ilyescat888** [SinisterRectus/Discordia#216]
local discordia = require("discordia")
local client = discordia.Client()
client:run("Bot (token)")
local monkynoise = client:getGuild("my server id")
local logs = monkynoise:getChannel("the logs channel")

client:on("ready", function() -- bot is ready
	print("Logged in as " .. client.user.username)
end)

client:on("messageCreate", function(message)
	local content = message.content
	local author = message.author
	if message.channel.guild.id == "522887932516761601" then
		logs:send(author.name .. "said: " .. 'message.content')
	end
end)

**Comment by ilyescat888** [comment]
attempt to index local 'monkynoise' (a nil value)

**Comment by TripTripy** [comment]
I believe you need to put your login at the end of your script. As well as make sure the id's for the guild and channel are strings and not integers

**Comment by SinisterRectus** [comment]
Sorry, I missed this one. Yes, you need to call `client:run` after setting up the event handlers, and you can only use methods like `client:getGuild` and `client:getChannel` after the client is "ready". Essentially, only use these methods inside of client event callbacks.
