### ISSUE TITLE
Missing "watching" gameType/activityType

### ISSUE THREAD

**Issue by antiafk** [SinisterRectus/Discordia#218]
In "enums.lua", is missing "watching" type. In my bot I implement "watching = 3" and did work.

**Comment by truemedian** [comment]
`watching` is not documented by Discord and is therefore not a supported feature, do not expect it to be enumerated until Discord adds it to the [documented activity types](https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-types)

**Comment by antiafk** [comment]
Ok, I understand.

**Comment by SinisterRectus** [comment]
See discordapp/discord-api-docs#463 and discordapp/discord-api#978
