### ISSUE TITLE
Voice Session is No Longer Valid Almost Immediately. 

### ISSUE THREAD

**Issue by TripTripy** [SinisterRectus/Discordia#219]
So I'm trying to add voice functionality to my bot. However, almost instantly after a voice connection is created, it becomes invalid. The bot stays in the voice channel for almost 30 seconds afterwards tho.
Here's the relevent code: 
`
client:on('voiceChannelJoin', function(member, channel)
  local connection = channel:join()
  coroutine.wrap(function()
44:    connection:playFFmpeg('rr.mp3', 10000)
    print('done streaming!')
  end)()

  print('start streaming')
end)`
and the log: 
`2019-10-30 22:02:43 | [INFO]    | Voice : Connected to wss://eu-west747.discord.media
2019-10-30 22:02:43 | [INFO]    | Voice : Received HELLO
2019-10-30 22:02:43 | [INFO]    | Voice : Connected to wss://eu-west747.discord.media
2019-10-30 22:02:43 | [INFO]    | Voice : Received HELLO
2019-10-30 22:02:43 | [INFO]    | Voice : Received READY
2019-10-30 22:02:43 | [INFO]    | Voice : Received READY
2019-10-30 22:02:43 | [WARNING] | Voice : 4006 - Session is no longer valid.
2019-10-30 22:02:43 | [INFO]    | Voice : Disconnected`
edit: forgot to mention, it errors with "bot.lua:44 attempt to index upvalue 'connection' (a nil value)"

**Comment by truemedian** [comment]
`channel:join()` should also optionally return an error string as the second argument, this might prove helpful in narrowing down the issue.

**Comment by TripTripy** [comment]
full error code `Uncaught exception:
...ents/DiscordBot/discordbot rewrite/deps/coro-channel.lua:119: ...ot rewrite/deps/discordia/libs/voice/VoiceConnection.lua:132: ...plapeeck\Documents\DiscordBot\discordbot rewrite\bot.lua:46: ...plapeeck\Documents\DiscordBot\discordbot rewrite\bot.lua:44: attempt to index upvalue 'connection' (a nil value)
stack traceback:
        [C]: in function 'assert'
        ...ents/DiscordBot/discordbot rewrite/deps/coro-channel.lua:119: in function <...ents/DiscordBot/discordbot rewrite/deps/coro-channel.lua:118>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
`

**Comment by truemedian** [comment]
`channel:join()` will be either returns `VoiceConnection` or `nil, err`, so you could do something like|
local connection, err = channel:join()
and then `print(err)` for more info.

**Comment by TripTripy** [comment]
Honestly, i didn't know that you could return multiple values like that. Im trying that now.
Heres the err: 'voice connection for channel xxxxxxxxx failed to initialize'

**Comment by SinisterRectus** [comment]
It looks like the bot is trying to join the channel on the voiceChannelJoin event. That should create an infinite loop. Try not doing this.

**Comment by TripTripy** [comment]
Oh god, didn't think of that. Is there better event to listen for when a user joins, or should i just return if the member is the bot?

**Comment by SinisterRectus** [comment]
You need to check that the member is not the bot.

**Comment by TripTripy** [comment]
Yeah, that's what i did. Thanks guys.
