### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by LoganDark** [SinisterRectus/Discordia#22]
I can see you've advanced quite a bit on this project, and I'd like to personally congratulate you on it. I'm sorry if I insulted you before about it, but I'd like to say it's looking pretty good.

**Comment by PurgePJ** [comment]
Pretty relevant _issue_.

**Comment by logandark** [comment]
I guess not, but this seems like the only place to contact Sinister Rectus. I can close my issue if you like, or somebody can close it for me. I don't care that much either way, I just wanted to congratulate him on his work.

**Comment by SinisterRectus** [comment]
Thank you. In the future, it my be better to comment on a [commit page](https://github.com/SinisterRectus/Discordia/commit/6873dc12c77fe50283f86c41a32f6817acc511cf) instead of opening an issue.

**Comment by LoganDark** [comment]
Understood.
