### ISSUE TITLE
Kicking and re-adding bot to guild results in client not caching this guild

### ISSUE THREAD

**Issue by BestMordaEver** [SinisterRectus/Discordia#226]
Steps to reproduce:
1. Start the bot
2. Kick the bot from guild
3. Add the bot to the same guild
4. Check client:getGuild(guild.id) - returns nil

Events guildCreate and guildDelete happen normally

**Comment by SinisterRectus** [comment]
The root cause of this issue is in the weak caching that I added with commit 4eefacad005903f6768654f0fbd53da9a7535e0f. I need to figure out how that change affects guild creation/deletion.

**Comment by SinisterRectus** [comment]
Oh I think I see it. When the bot is kicked, the guild object is moved the cache's `_objects` table to its `_deleted` table. When the bot is re-added, the old guild object from the `_deleted` table is used (assuming it was not collected), but it is never put back into the `_objects` table.

**Comment by SinisterRectus** [comment]
That should fix it. You can manually update `Cache.lua` to test it. I will try to get a release out, but there are some other things I want to work on before then.
