### ISSUE TITLE
String:split(" ") is not working.

### ISSUE THREAD

**Issue by TheFortex** [SinisterRectus/Discordia#227]
in the examples and tutorials you made you seem to use the function `:split()`

here is a line from your example scripts in Discordia files

`local args = message.content:split(" ")`

I know of this function and i have tried to use it before and it seemed like it wasn't supported by the current version of Lua but then i saw your examples and copy-pasted it and it still does **not** work. I tried running your script itself still doesn't work. It always returns the error `attempt to call method 'split' (a nil value)`

I have gotten around it using a function of my own
```lua
function split(str)
    local tbl = {}
    for i in string.gmatch(str, "%S+") do
       table.insert(tbl, i)
    end
    return tbl
end
```

So I'm not sure if it's a code error or just an old Lua version, either way, you should remove it from the examples or fix it.

**Comment by SinisterRectus** [comment]
It's an extension: https://github.com/SinisterRectus/Discordia/wiki/Extensions
