### ISSUE TITLE
Problem with script.

### ISSUE THREAD

**Issue by skrampy63** [SinisterRectus/Discordia#228]
There is problem with:
local memberid = message.member.id
I dont know what is wrong with it. It is crashing not in regular time, sometimes it is 10 minutes sometimes 30 seconds.
there is it:
![image](https://user-images.githubusercontent.com/60897372/74183460-4908f680-4c45-11ea-86c3-becb5fea9828.png)

**Comment by skrampy63** [comment]
Should I give the whole code?

**Comment by SinisterRectus** [comment]
As documented, it is possible for the `message.member` property to be `nil`. For example, in message authored by webhooks or by authors who have left the guild, or if for some reason the member is simply not cached.

**Comment by skrampy63** [comment]
It crashed, when I wasn't doing anything.

**Comment by SinisterRectus** [comment]
Whether you were actively doing anything does not matter. According to the error message, your code at line 59 of myworld.lua crashed because it tried to index a nil value.

**Comment by skrampy63** [comment]
so what is wrong with it:
![image](https://user-images.githubusercontent.com/60897372/74184382-fdefe300-4c46-11ea-809a-9ae0b5a6cb6d.png)

**Comment by skrampy63** [comment]
should i change now every memberid to message.member.id and remove:
local memberid?

**Comment by Geo1088** [comment]
No, that wouldn't help. You need to use an `if` to check if `message.member` is nil before trying to get its `id`. If it is `nil`, you probably want to stop the function early by `return`ing.

**Comment by skrampy63** [comment]
this should work?:

if not message.member.id == nil then
	local memberid = message.member.id
end

**Comment by Geo1088** [comment]
```lua
if message.member == nil then
	return
end
```

Just put this before you try to do anything with `message.member.id`. It will make sure that if `message.member` is `nil`, it will just stop processing the message before it errors out.

Your code is breaking because you're not accounting for all possible cases that this event could fire. If your bot receives a DM, then the message isn't in a server, but a DM channel, and so there will be no `member`, since `member` represents a user's connection to a server. Did you maybe mean to use `author` instead?

**Comment by greasemonkey123** [comment]
Here's the issue;
If you're trying to find the ID of the member who sent the message, use `local memberid = message.author.id`. It won't return nil, even if it was sent in a DM.

Also, what you're trying to find is a non-existing value. `member` doesn't have an ID property. However, you can use message.member.user.id, which will return the User **ONLY** if the member is inside a guild.

**Comment by SinisterRectus** [comment]
I think this was resolved on the support server.
