### ISSUE TITLE
HTTP Errors

### ISSUE THREAD

**Issue by TehDino** [SinisterRectus/Discordia#230]
Is there an option to disable sending api failure errors into the console?

**Comment by TehDino** [comment]
Or catch them in any way?

**Comment by SinisterRectus** [comment]
Those are two opposing questions. Are you looking to ignore errors or handle them?

**Comment by TehDino** [comment]
I would rather handle them.

**Comment by SinisterRectus** [comment]
Most errors should be handled on a case by case basis. Discordia methods that make HTTP requests will return `nil, err` for failures. For example, if `channel:send()` produces a a 4xx error, then the returned values will be `nil` and some `err` message string. You should check that string to see more details about what went wrong and fix your code to prevent it from happening again.

**Comment by TehDino** [comment]
But then that leads to http errors in the console, which is what I am trying to avoid. So what should I do to prevent them?

**Comment by SinisterRectus** [comment]
You cannot selectively disable error logging. You can set the `logLevel` in client options to `0` (none), but this will stop all logging. I don't recommend doing that. You should instead make an attempt to prevent the errors from occurring when possible.

**Comment by TehDino** [comment]
What would you suggest as the best option to say, ex: check if a member exists in a guild while preventing an error. Knowing guild:getMember(id) would error if the member does not exist.

**Comment by Mehgugs** [comment]
You can't: it's supposed to give you an "error".

**Comment by TehDino** [comment]
That's why I made this issue, was kinda hoping there was a solution. But looks like changing the log level will be the best bet.

**Comment by Mehgugs** [comment]
Why do you not want it in the logs? You know it's not an issue, and the word error doesn't automatically mean bad especially not for a restful api.

**Comment by TehDino** [comment]
Not really useful when I know what causes, but still cannot prevent it while it floods the console.

**Comment by SinisterRectus** [comment]
What is your bot doing where it has to make a lot of calls to `getMember`?

**Comment by TehDino** [comment]
Not necessarily making lot's of getMember calls, that was used as an example. But my bot checks if a user exists in a certain guild using getMember per command.

**Comment by SinisterRectus** [comment]
Then why are the logs an issue?

**Comment by TehDino** [comment]
Again, they flood the console. Which isn't a good sight. But changing the log level will do.
