### ISSUE TITLE
I Can't use 'GuildTextChannel' (I am stupid.)

### ISSUE THREAD

**Issue by Bit-Laura** [SinisterRectus/Discordia#231]
I don't know if I'm stupid or if this is weird, but I don't know how to use 'GuildTextChannel'. I want to make a code to confirm that the current channel is nsfw channel. Somebody help me!

**Comment by Bilal2453** [comment]
```lua
if message.channel.nsfw then p('The channel is NSFW') end
```

I really suggest on you reading the [wiki](https://github.com/SinisterRectus/Discordia/wiki), especially [Writing your First Bot](https://github.com/SinisterRectus/Discordia/wiki/Writing-Your-First-Bot)

Also, if you want help with making your bot, you shouldn't be opening an issue, instead, join this discord server **https://discord.gg/discord-api** and ask in #lua_discordia.

**Comment by Bit-Laura** [comment]
Oh, I didn't know there was a Wiki.... Thank you very much!

**Comment by Bilal2453** [comment]
@Bit-Laura If your issue is solved, please consider closing this issue.
