### ISSUE TITLE
If statements do not register “and”

### ISSUE THREAD

**Issue by SebWil** [SinisterRectus/Discordia#233]
If I have some code like this 
```
local a = true
local b = false

if a and b then print(“both are true”) end
```
It will ignore the fact that b is false and will say that both are true, Ive also found that just inputting the variable without including some form of “if a==true then” will also result in problems.

**Comment by Xh4H** [comment]
And is this an issue for this library?

**Comment by Xh4H** [comment]
If you are seeking for help, provide the real code as this piece of code evaluates properly:

![image](https://user-images.githubusercontent.com/20613820/79004416-01272280-7b55-11ea-886c-7e4ebc9d0de5.png)
