### ISSUE TITLE
How do i send a message to a specific channel?

### ISSUE THREAD

**Issue by Maizenito** [SinisterRectus/Discordia#236]
I want to send a message to a specific channel, can you guys please help me?

**Comment by Bilal2453** [comment]
1. Fetch that channel, probably using `guild:getChannel(ID)` ID has to be string.
2. Basically use send method `fetchedMessage:send("Message")`.

Please, for help with using Discordia, Join this server and ask us there (In discordia channel) !!
https://discord.gg/discord-api
