### ISSUE TITLE
Could Not Authenticate, check token

### ISSUE THREAD

**Issue by superbolt999** [SinisterRectus/Discordia#239]
Whenever I run the code, there would be the third error line and it would say
#1:TLS not supported
Maybe [SSLv3] SSLv23 TLSv1 TLSv1_1 TLSv1_2 DTLSv1 [SSLv2], option followed by _client or _server
default is TLSv1

how do I fix this?

**Comment by SinisterRectus** [comment]
In your bot directory, can you please run `lit ls` and `luvit -v` and paste here the output of both.

**Comment by superbolt999** [comment]
lit ls
![image](https://user-images.githubusercontent.com/65319081/81880155-ebd55780-9549-11ea-9dce-a3e429cb607e.png)
luvit -v
![image](https://user-images.githubusercontent.com/65319081/81880180-03144500-954a-11ea-84a3-04d8b43d204c.png)

**Comment by SinisterRectus** [comment]
This is a sort of common issue that results from a mismatch between OpenSSL and (I think) the secure-socket library. Somehow, your luvit and dependencies are all up to date, but your luvi (and the OpenSSL that it comes with) is not. Try re-installing luvit to a new directory. It should be 2.17.0, but the luvi version should be 2.10.1.

**Comment by superbolt999** [comment]
that completely fixes it thanks!
