### ISSUE TITLE
Can't get guild?

### ISSUE THREAD

**Issue by Cboat** [SinisterRectus/Discordia#244]
I am trying to get access to the guild my bot is in, I am an administrator in the server. 
This is nil, local server = client:getGuild("713553105005969500")
I'm fairly experienced in Lua, but not with Discordia. Any help is greatly appreciated!

**Comment by SinisterRectus** [comment]
Looks okay to me. The only reason why this should fail is if the bot is not in the guild. Please visit the #lua_discordia channel at https://dscord.gg/discord-api to debug this.

**Comment by Cboat** [comment]
It's 100% in the guild, I am using a command inside the guild to kick someone so It's definitely in there.

**Comment by Cboat** [comment]
I also copied the ID in multiple different ways.

**Comment by Cboat** [comment]
Such a weird issue. The server variable is nil.

**Comment by object-Object** [comment]
If you visit the #lua_discordia channel in https://discord.gg/discord-api we can help debug this more easily.

**Comment by Cboat** [comment]
I am in the server, just waiting the 10 minutes.
