### ISSUE TITLE
Bot automatically shuts off

### ISSUE THREAD

**Issue by iiToxicity** [SinisterRectus/Discordia#246]
I'm not sure if I'm doing something wrong, but I'm launching like 6 bots at a time on my VPS, and some of them randomly just shut off. 

I open the CMD Prompt and type in a key and they restart themselves. Is this an issue with stacking multiple bot prompts on top of each other, or something I'm just not aware of? Literally, like 2 bots will go inactive, then all the other ones stay online.

**Comment by Bilal2453** [comment]
That sounds like not enough memory problem. Can you make sure that when you run all of the bots and just before any go offline you would have enough memory till one of the bots go offline?

**Comment by iiToxicity** [comment]
> That sounds like not enough memory problem. Can you make sure that when you run all of the bots and just before any go offline you would have enough memory till one of the bots go offline?

Hm, I've never thought about that being the issue. I only have 2GB ram for my VPS, it's constantly running at about 60-70% though. It always goes offline when I'm asleep and my clients notify me of this.

**Comment by Bilal2453** [comment]
I would suggest monitoring your memory usage, probably something such as constantly logging memory usage into **disk** (every fife minutes or so). Or even better, using a memory profiler that is compatible with Luvit to exactly determine what call is doing that.

Also make sure that user commands don't take huge memory. And never use the `p` and `print` functions in the final version of the bot.

You could also host all the bots at your own machine (that should have memory more than your VPS does) and see if same problem occurs or not, if it doesn't then you can confirm, memory usage is your issue on the VPS.

Hope that helps you, and I can confirm to you that stacking bots works fine on my own machine, so the problem has nothing to do with Discord itself, or Luvit.

Good luck.

**Comment by SinisterRectus** [comment]
Has this been solved?

**Comment by iiToxicity** [comment]
It has not been solved. It might be due to the fact I'm using a windows VPS. They can be restarted by clicking on the command prompt and typing in something random though.

**Comment by Bilal2453** [comment]
That's unfortunate news. Can you provide us what method have you tried? did you monitor your VPS memory usage? or maybe hosting on your own machine to see if that happens there?

Does that always happen even when you only run one of the bot that uses to suddenly stop working?

Other than that, can you provide the technical details, what is the version of Discordia, Luvit, Luvi, and the machine basic details such as memory (RAM), system, and CPU.

And another really important question, how are you exactly running your bots, are you just starting them of by using a batch file (.bat, .cmd), or something else?

I suggest you visiting Discordia's channel at [DAPI Discord](https://discord.gg/discord-api), we can have a direct chat there.

Good luck.

**Comment by SinisterRectus** [comment]
With the reply above, I'm going to close this. If evidence that this is a library issue is discovered, we can reopen it. Until then, visit the support channel linked above.
