### ISSUE TITLE
Reactions Fail

### ISSUE THREAD

**Issue by iiToxicity** [SinisterRectus/Discordia#247]
I'm again, not sure if it's just me or if Discordia's API is bad with this sort of thing. When I add a reaction using "addReaction", if I react to that message that has reactions about 10 minutes later on my own account, the "reactionAdd" event doesn't pick up that I've added a reaction. This limits me from making giveaway bots and such.

**Comment by truemedian** [comment]
Discordia has 2 separate events for reactions, `reactionAdd` for when the message is cached and `reactionAddUncached` for when the message is uncached and all Discordia knows about is that a reaction was added. If you want to handle reactions, you must handle both of these events.

**Comment by iiToxicity** [comment]
Ohh! Thanks, I wasn't aware of this. I'll fix my bots soon!
