### ISSUE TITLE
[Fixed]the bot breaks when someone dm's it

### ISSUE THREAD

**Issue by m7md8d** [SinisterRectus/Discordia#251]
it breaks for some reasons even when it sends a dm to someone
[EDIT] fixed!

**Comment by KaloHG** [comment]
Are you sure you have it installed properly? 

You're gonna need to describe a bit more than just "it crashes when someone DM's it." Since I am unable to reproduce said crash.

**Comment by m7md8d** [comment]
the bot crashes\breaks when someone sends a dm message to the bot and when i use the message.member:send("something") it also breaks/crashes and i get this message


stack traceback:
        [C]: in function 'assert'
        ...ers/ADMINISTRATOR/Desktop/shitbot/deps/coro-channel.lua:62: in funct
ion 'onPlain'
        ...ADMINISTRATOR/Desktop/shitbot/deps/secure-socket/biowrap.lua:76: in funct
ion <...ADMINISTRATOR/Desktop/shitbot/deps/secure-socket/biowrap.lua:61>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:4
7>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:dep
s/require.lua"]:266>


and it's the only issue that im getting

**Comment by SinisterRectus** [comment]
How are you checking that the message is a DM?

**Comment by m7md8d** [comment]
i've just tested it i told members from my server to message the bot/dm the bot and it was randomly crashing and then
i DMd the bot the same thing happened it crashed  also when i do something like
if message.content == "@test" then
message.member:send("a message") 
end
it will send a message to the member who said @test and then crashes

**Comment by NotSoClassy** [comment]
Well your trying to get a member object from a dm. You can only get members from guilds

**Comment by m7md8d** [comment]
bro that's not the problem even when a random guy sends a message to the bot it crashes[not in a server just a DM message] and now it crashes when it sends an embed message or another bot does also when someone uploads a gif or a picture

**Comment by KaloHG** [comment]
So there is this cool little button called "Close Issue" please press it.
