### ISSUE TITLE
400 - Bad Request when attempting to add a reaction.

### ISSUE THREAD

**Issue by WiiShopChannel** [SinisterRectus/Discordia#255]
```lua
        local msg = message.guild:getChannel("671069781931065374"):send({embed = {
            ['fields'] = {
                {['name'] = "Submitter", ['value'] = message.author.name.."#"..message.author.discriminator};
                {['name'] = "Suggestion", ['value'] = suggestion};
            };
            ['footer'] = {
                ['text'] = "User ID: "..message.author.id
            };
            ['color'] = 0x2d4a69;
            ['thumbnail'] = {['url'] = message.author.avatarURL} 
        }})
        message:delete()
        msg:addReaction("👍")
        msg:addReaction("👎")
```

Code Above. It should be adding a reaction to the message created, but is giving a 400 error in the console.

**Comment by Bilal2453** [comment]
What's your Discordia version?
since this might be a verified bug in Discordia <=2.6.0 and was fixed in new releases. Make sure you are running latest version and Discordia is up to date.

**Comment by WiiShopChannel** [comment]
> What's your Discordia version?
> since this might be a verified bug in Discordia <=2.6.0 and was fixed in new releases. Make sure you are running latest version and Discordia is up to date.

Most likely a pretty old one as I started using discordia in 2017 and haven't really updated. I'm not sure how to check but I'll update right now.
