### ISSUE TITLE
Message.embed is nil when the bot sends the message

### ISSUE THREAD

**Issue by Hilyr** [SinisterRectus/Discordia#257]
And weirdly enough this only seems to happen for lightshot.
So if a bot sends something like this:
"http://prntscr.com/flafz"
The message.embed will be nil, even though there's an embed.

![image](https://user-images.githubusercontent.com/57411166/91067823-b0135900-e633-11ea-977a-a8298b15b555.png)

But if it's for something else like a YouTube link the message embed works.

**Comment by SinisterRectus** [comment]
The embed is not provided by Discord in the original message object. It comes in a messageUpdate event.
