### ISSUE TITLE
"module 'class' not found"

### ISSUE THREAD

**Issue by ElpersonPL** [SinisterRectus/Discordia#258]
```
C:\Users\elper\Desktop\LUA IDE\lualibs/discordia/init.lua:2: module 'class' not found:
	no field package.preload['class']
	no file '.\class.lua'
	no file 'C:\Users\elper\Desktop\LUA IDE\bin\lua\class.lua'
	no file 'C:\Users\elper\Desktop\LUA IDE\bin\lua\class\init.lua'
	no file './class.lua'
	no file './class/init.lua'
	no file './lua/class.lua'
	no file './lua/class/init.lua'
	no file 'C:\Users\elper\Desktop\LUA IDE\lualibs/class/class.lua'
	no file 'C:\Users\elper\Desktop\LUA IDE\lualibs/class.lua'
	no file 'C:\Users\elper\Desktop\LUA IDE\lualibs/class/class/init.lua'
	no file 'C:\Users\elper\Desktop\LUA IDE\lualibs/class/init.lua'
	no file '.\class.dll'
	no file 'C:\Users\elper\Desktop\LUA IDE\bin\class.dll'
	no file 'C:\Users\elper\Desktop\LUA IDE\bin\loadall.dll'
	no file 'C:\Users\elper\Desktop\LUA IDE\bin/clibs/class.dll'
```
After putting all the stuff I downloaded from lit into the IDE folder.
(Windows 10)

**Comment by SinisterRectus** [comment]
You need to run Discordia bots with Luvit.

**Comment by ElpersonPL** [comment]
`dofile "C:/Users/elper/deps/Discordia/examples/pingPong.lua"
C:/Users/elper/deps/Discordia/examples/pingPong.lua:1: module 'discordia' not found:
        no field package.preload['discordia']
        no file '.\discordia.lua'
        no file 'C:\Users\elper\lua\discordia.lua'
        no file 'C:\Users\elper\lua\discordia\init.lua'
        no file '.\discordia.dll'
        no file 'C:\Users\elper\discordia.dll'
        no file 'C:\Users\elper\loadall.dll'
stack traceback:
        [C]: in function 'require'
        C:/Users/elper/deps/Discordia/examples/pingPong.lua:1: in main chunk
        [builtin#26]: at 0x7ff6f6d9f0f0
        [C]: in function 'xpcall'
        [string "bundle:/deps/repl.lua"]:97: in function 'evaluateLine'
        [string "bundle:/deps/repl.lua"]:189: in function <[string "bundle:/deps/repl.lua"]:187>
`
Although all of the files that were downloaded from lit are there.

**Comment by Bilal2453** [comment]
By "you need to run it using Luvit" it means that you should use the console up and type `luvit pingPong.lua` or whatever is the main file name. Also make sure that you require Discordia through `require("discordia")` nothing less.

**Comment by Bilal2453** [comment]
There is a whole guide about how to start the bot on the Github wiki page, at the [Beginner](https://github.com/SinisterRectus/Discordia/wiki#beginner) section, I recommended reading all of that section, but for this matter you want to take a look at [Writing Your First Bot](https://github.com/SinisterRectus/Discordia/wiki/Writing-Your-First-Bot) (specifically Step 5).

Good luck.

**Comment by ElpersonPL** [comment]
> By "you need to run it using Luvit" it means that you should use the console up and type `luvit pingPong.lua` or whatever is the main file name. Also make sure that you require Discordia through `require("discordia")` nothing less.

`C:\Users\elper\deps\discordia\examples>luvit pingPong.lua
'luvit' is not recognized as an internal or external command,
operable program or batch file.`
I can only do luvit in the `C:/Users/elper` directory

**Comment by Bilal2453** [comment]
You need to set up Luvit at your system PATH or just `cd` into where Luvit is installed. Since this is no more Discordia related issue (and questions shouldn't be asked here anyways), you should come up and visit Discordia's support channel at [Discord API guild](https://discord.gg/discord-api). We can provide better support at there :)
