### ISSUE TITLE
Issue with guild members and client options...kinda

### ISSUE THREAD

**Issue by ajloveslily14** [SinisterRectus/Discordia#262]
Basically, on a client(which yes I know, shouldn't be done) if you add either 'cacheAllGuildMembers' or 'syncGuilds' the process will freeze for seeming forever, I think it may be waiting for data that it'll never get or something. 

also, Guild:requestMembers() silently fails I believe when it's called

Not really an issue because as stated before, this use case should ideally never happen, but it's just something I've noticed.

I'm sure it has to do with the privileged intents and all that nonsense.

**Comment by truemedian** [comment]
`syncGuilds` has no effect on bots, and `cacheAllMembers` merely calls `requestMembers` on the guild as they become available.

`Guild:requestMembers` happens asynchronously, so unless you're saturating your bandwidth with loading members, you shouldn't notice anything. If you're in multiple large servers, I recommend turning off `cacheAllMembers` simply for memory reasons, but it will also stop the *rather slow* process of caching members.

**Comment by ajloveslily14** [comment]
Hm that could be it. I just know calling requestMembers, then checking how many members there are doesn't increase it at all, at least that ive noticed.

**Comment by truemedian** [comment]
No. There is no issue here, `requestMembers` happens asynchronously behind the scenes, there are no events to tell you when its done. It will *relatively* slowly populate the member cache with members over time. Checking for a difference before and after calling `requestMembers` will yield no difference, because no member chunks have been received yet.

**Comment by ajloveslily14** [comment]
ah ok, i had figured requesting members would do it faster than it is. is it any faster than just letting the cache naturally grow?

**Comment by truemedian** [comment]
It's absolutely faster than letting it naturally grow because you force every member to be cached, but unless you really need to have every member cached, its usually a better idea to use `guild:getMember` to fetch a member object when you need it. Also much nicer on memory for large servers.

**Comment by ajloveslily14** [comment]
I thought so, but I have tested and noticed, that when you do this:
```lua
g = client:getGuild("<id>")
print(#g.members)
g:requestMembers() --say this guild has 1000 members
```
wait an hour, and then print #g.members again, it wont have gone up by much at all, note this is all in the context of being ran on a user account, not a bot one.

**Comment by truemedian** [comment]
Discordia's support for user accounts is all legacy code given the whole self-bot ban. Discord has changed how users get members, so don't expect anything to work there. You also won't find much help for running Discordia on a user account here because it is against Discord's Terms of Service.

**Comment by ajloveslily14** [comment]
yes i am fully aware of that, i just wanted to mention that those functions and options just stall the bot into a loop on user accounts.

a bug is a bug, whether or not it's a rule breaking one or not. id just remove it tbh

**Comment by Bilal2453** [comment]
A bug is a bug, and this one won't be fixed because Discordia no more supports user-bots, Discordia 3.x will even completely drop the support for that. Therefor no plans on fixing any bugs that only exists with user-accounts, if you really do want it to be fixed you will -in most cases- need to fix it yourself, don't expect much support with it.

**Comment by ajloveslily14** [comment]
I wasn't expecting a fix or a support I was just reporting a bug man
