### ISSUE TITLE
bruh help me pls

### ISSUE THREAD

**Issue by thaikair** [SinisterRectus/Discordia#264]
idk if its just me but is anything working for u? like createdAt() and basically every function gives me an arror
![image](https://user-images.githubusercontent.com/70456004/94975981-46a32780-04c8-11eb-81de-fbec115e5d3f.png)

**Comment by SinisterRectus** [comment]
Hi. To get help with your code, please either join https://discord.gg/NKM3XmF or https://discord.gg/EzRYYDW.
