### ISSUE TITLE
getRole issue

### ISSUE THREAD

**Issue by NougatBitz** [SinisterRectus/Discordia#268]
getRole(766799441310908466)

just errors and says that the URL is invalid...

**Comment by SinisterRectus** [comment]
It should be a string. Try `"766799441310908466"`.

**Comment by NougatBitz** [comment]
omg, i legit Spent multiple Hours trying to find the issue, tysm!

**Comment by NougatBitz** [comment]
Uhh, now it says:

2020-10-18 02:00:56 | [ERROR]   | 403 - Forbidden : PUT https://discord.com/api/v7/guilds/759149557383954434/members/674631775913377812/roles/766799441310908466

**Comment by SinisterRectus** [comment]
It says forbidden. That means the bot doesn't have permission to add the role.
