### ISSUE TITLE
Add name property to TextChannel documentation

### ISSUE THREAD

**Issue by RanDumSocks** [SinisterRectus/Discordia#279]
The TextChannel class has a name property, but it is not documented on [the wiki page](https://github.com/SinisterRectus/Discordia/wiki/TextChannel).

I was just confused why it wasn't documented is all, and think quickly adding that wouldn't hurt.

**Comment by truemedian** [comment]
The TextChannel class does not have a name property, only the user-facing GuildTextChannel, PrivateChannel and GroupChannel have names, because they obtain them from different places. The TextChannel class is abstract.
