### ISSUE TITLE
QUESTION. How to add custom emoji to embed? 

### ISSUE THREAD

**Issue by eseeseuwawa** [SinisterRectus/Discordia#281]
Im new to discordia and wondering how do you add a custom discord emoji to an embed? What are the steps taken?

**Comment by Bilal2453** [comment]
Hey there! glad you are liking Discordia so far. If you want to ask some questions and have support we have a community just for you! Join us at [our server](https://discord.gg/EzRYYDW) or at our channel in [DAPI](https://discord.gg/discord-api).

Good luck!
