### ISSUE TITLE
Getting user with name

### ISSUE THREAD

**Issue by HunterAPI** [SinisterRectus/Discordia#286]
Is there a way to get a user with the user's name instead of their id like for Dyno, you can do `cmd [name]` and it'll do it to the user with that name. This is how I get the user with the id from id or mention. `local user = client:getUser(msg.mentionedUsers[1] and msg.mentionedUsers[1][1] or str:match("^%s*(%d+)") or msg.author.id)`

**Comment by object-Object** [comment]
We'd be happy to answer support questions in the [Discord API](https://discord.gg/discord-api) (`#lua_discordia`) or [Discordia](https://discord.gg/EzRYYDW) servers. Github issues are meant for bug reports, etc.

**Comment by HunterAPI** [comment]
Oh, my bad. Thanks.
