### ISSUE TITLE
404 error when a message is deleted in any channel

### ISSUE THREAD

**Issue by SharkTheScripter** [SinisterRectus/Discordia#289]
Hi, I'm trying to make a feature where the bot detects deleted messages using this code:

```lua
client:on("messageDelete", function(message)
	pcall(function()
		local infoTable = {
			content = message.content;
			user = message.user
		}
		deletedMessages[message.channel.id] = infoTable
	end)
end)
```

For some reason, however, it's popping up with 404 errors and not detecting these deleted messages. Is there something I can do to fix this? Thanks!

![image](https://user-images.githubusercontent.com/76228240/115125995-90012300-9f91-11eb-8b0b-7fabaa679515.png)

**Comment by truemedian** [comment]
Those errors are unrelated to that code. The error is telling you that a member you're trying to request via `Guild:getMember` doesn't exist.

On another note: `message.user` doesn't exist.

**Comment by SharkTheScripter** [comment]
The errors appear every time a message is deleted.

**Comment by object-Object** [comment]
We'd be happy to answer support questions like this one in the [Discord API](https://discord.gg/discord-api) (`#lua_discordia`) or [Discordia](https://discord.gg/EzRYYDW) servers.

**Comment by leXinshou** [comment]
Before you do anything, please do check https://github.com/SinisterRectus/Discordia/wiki/Message

The message.user doesn't exist, however message.member or message.author exist.
