### ISSUE TITLE
Client crashes when not able to connect in a voice channel (have no permission or a shitty internet)

### ISSUE THREAD

**Issue by D4rknessKing** [SinisterRectus/Discordia#29]
`Sat Dec 24 18:06:47 2016 - Failed to join voice channel: 254023371958779905
Uncaught Error: .../Desktop/L1ghtBeta/deps/discordia/voice/VoiceManager.lua:58: attempt to index local 'connection' (a nil value)
stack traceback:
	.../Desktop/L1ghtBeta/deps/discordia/voice/VoiceManager.lua:58: in function 'callback'
	[string "bundle:deps/timer.lua"]:97: in function <[string "bundle:deps/timer.lua"]:94>
	[C]: in function 'run'
	[string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
	[C]: in function 'xpcall'
	[string "bundle:init.lua"]:47: in function 'fn'
	[string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
`

**Comment by SinisterRectus** [comment]
I will fix this bug the first chace I get. I may also reduce the timeout delay length, and add a permissions check to reduce the chance of a failed attempt to join a channel.

**Comment by SinisterRectus** [comment]
Commit da7b35822a8ba86e12f4d352daae4ace45c9ef6c should address this issue. Feel free to test the GitHub files, or wait for the next Discordia release.
