### ISSUE TITLE
400 error when getting the Old content of a edited message

### ISSUE THREAD

**Issue by GTNTAnimations** [SinisterRectus/Discordia#291]
I was trying to get the old content of an edited message with Discordia however I got an error with the code 400
Code:
```
local discordia = require('discordia')
local client = discordia.Client()

client:on("messageUpdate", function(message)
	message:reply(message.Oldcontent)

end)


client:run('Bot [token]')
```
Error:
`| [ERROR]   | 400 - Bad Request : POST https://discord.com/api/v7/channels/840939589803048980/messages`

**Comment by SinisterRectus** [comment]
`message.OldContent` is not a property, it is `message.oldContent`; however, it can be `nil` or a special `table`, neither of which are acceptable formats for sending messages.

Please read [this page](https://github.com/SinisterRectus/Discordia/wiki/Managing-messages) on messages or join us at https://discord.gg/EzRYYDW for support.
