### ISSUE TITLE
Trying to send image in embed

### ISSUE THREAD

**Issue by llamaWol** [SinisterRectus/Discordia#295]
I'm trying to send an image in an embed, in py there's a function called set_image(url) for it, but I can't seem to find something that does the same in discordia...

**Comment by senor-init** [comment]
you can pass a table to send/reply to format the message you want to send
see:
https://github.com/SinisterRectus/Discordia/wiki/Managing-messages#file

also, there's a discordia channel in [discord-api server](https://discord.gg/discord-api) and a [discordia server](https://discord.gg/sinisterware) where you can ask such questions

**Comment by llamaWol** [comment]
Okay, thanks

**Comment by senor-init** [comment]
do you mind closing this issue?
