### ISSUE TITLE
member properties not but but name 

### ISSUE THREAD

**Issue by Jackmods12** [SinisterRectus/Discordia#299]
every time I try to print any property but name it returns nil

client:on("messageCreate", function(message)
    local member = message.author
    if message.content == prefix.. "Hello" then
        print(member.name)
        print(member.joinedAt)
    end

    if message.channel.id == "721803170539372564" then
        message:addReaction("👍")
        message:addReaction("👎")
    end
    
end
)

**Comment by senor-init** [comment]
hi jack, please keep in mind that author !== member and proprieties such nickname, joinedAt, etc aren't a part of the object `author/user`

**Comment by opBandwidth** [comment]
Are you sure you're doing it correctly? `message.author` returns User container therefore if you do `message.author.name` will be the same as `user.name` or `user.username`..

```lua
client:on("messageCreate", function(message)
        print(message.author.name)
end)
```

**Comment by SinisterRectus** [comment]
If you need further help with this, please visit the #discordia-help or #lua-help channels at https://discord.gg/sinisterware or the #lua_discordia channel at https://discord.gg/discord-api.
