### ISSUE TITLE
Game status returns nil on larger servers.

### ISSUE THREAD

**Issue by XNBlank** [SinisterRectus/Discordia#3]
Attempting to retrieve `member.gameName` from members on larger servers (Assuming > 100) returns a nil value. 

DiscordAPI Server (1000+ (?))
![](http://i.imgur.com/rVHv6IQ.png)
![](http://i.imgur.com/gnDu76L.png)

Discord Linux (600+ users)
![](http://i.imgur.com/PL8t6hB.png)
![](http://i.imgur.com/8pCBHUn.png)

My Test Server (4 users)
![](http://i.imgur.com/Nz3rZkK.png)

**Comment by SinisterRectus** [comment]
Hopefully fixed with da1a2517a1c966d229c4d9668acfd4aeca1330f8

**Comment by XNBlank** [comment]
Confirmed fixed.
