### ISSUE TITLE
401 - Unauthorized : GET https://discord.com/api/v7/users/@me and Could not authenticate, check token: HTTP Error 0 : 401: Unauthorized

### ISSUE THREAD

**Issue by Suprewing** [SinisterRectus/Discordia#303]

**Comment by nue-houjuu** [comment]
assuming you were passing your right token, in discordia 2.x you have to prefix it with `Bot `

**Comment by LuaLighter** [comment]
I have the same error. How do I prefix it?

**Comment by Bilal2453** [comment]
Prefix it, as in pass `Bot TOKEN`, replace `TOKEN` with your real token (and not client secret).

**Comment by LuaLighter** [comment]
I just thought that was a placeholder. that makes so much sense

**Comment by pandasoli** [comment]
"real token" you mean client id?
It didn't work with client id too
