### ISSUE TITLE
[dev] Interactions from message components don't account for the message they're from having flags = 64

### ISSUE THREAD

**Issue by TheOneBOB** [SinisterRectus/Discordia#304]
When the library goes to make a new interaction instance it doesn't check if the message the components are from has flags = 64 or not. Through my own testing it appears that when the message has flags = 64 Discord doesn't provide message data except the flags and id values. So all of this put together causes an error.

**Comment by SinisterRectus** [comment]
I wrote the class based on the [Discord docs](https://discord.com/developers/docs/interactions/slash-commands#interaction-object-interaction-structure), which do not indicate that the message object may be partial. I'll have to look into this, thanks for the report.

**Comment by SinisterRectus** [comment]
I'm told that this will be fixed in the API soon.

**Comment by TheOneBOB** [comment]
Yep looks like it has been.
