### ISSUE TITLE
Detects when a reaction is added

### ISSUE THREAD

**Issue by iiRezux** [SinisterRectus/Discordia#322]
Hello, thanks for help in advance, I am a beginner and I barely made a bot that add reactions to his messages, and I want it to detect what reaction did the user click/add
https://i.imgur.com/Q1PEluZ.png
and Thanks.

**Comment by object-Object** [comment]
You're looking for the `reactionAdd` and `reactionAddUncached` events and/or the `client:waitFor` method. Also, it's generally easier, better, and faster to ask questions like this in the [Discord API](https://discord.gg/discord-api) or [Discordia](https://discord.gg/sinisterware) servers.

**Comment by XeneonPlays** [comment]
how?

**Comment by Bilal2453** [comment]
Please redirect your question to [Discord API](https://discord.gg/discord-api) or [Discordia](https://discord.gg/sinisterware). This place is for reporting actual bugs with Discordia. Good luck.
