### ISSUE TITLE
Discordia randomly starts giving the error : "bad argument #4 in logger.lua"

### ISSUE THREAD

**Issue by wildyShadow** [SinisterRectus/Discordia#326]
Hello!, so, i were using discordia for doing my bot, it was working normally then suddenly a error started appearing and it is inside discordia code,
this is the error im given :
`bad argument #4 to fomat in logger.lua line 70, (expected number, got nil)`
i dont know whats happening, i didnt edit the code or anything, so if you could fix it then thanks

btw im from brazil, any error in the speaking was acidental

**Comment by BlindDaemon** [comment]
Discordia doesnr just give  random errors out of the blue. The problem is likely something you were doing. Try debugging your code and see if you can isolate the exact cause of it.

**Comment by wildyShadow** [comment]
> Discordia doesnr just give random errors out of the blue. The problem is likely something you were doing. Try debugging your code and see if you can isolate the exact cause of it.

It actually did, i

**Comment by wildyShadow** [comment]
> Discordia doesnr just give random errors out of the blue. The problem is likely something you were doing. Try debugging your code and see if you can isolate the exact cause of it.

It actually did, i started the bot and it gave out a error, i stopped coding on it and on the next day it stopped

**Comment by Bilal2453** [comment]
Can you show full traceback? and your code please? this is most likely due to you using `Logger:log` without passing the proper arguments. For proper help I hope you redirect your question to our [Discord](https://discord.gg/sinisterware)

**Comment by wildyShadow** [comment]
> Can you show full traceback? and your code please? this is most likely due to you using `Logger:log` without passing the proper arguments. For proper help I hope you redirect your question to our [Discord](https://discord.gg/sinisterware)

i never used logger:log, The error Just started happening randomly and stopped in the next day, the code is fine i tested it and it worked perfectly, when the error was happening i deleted the client:run() and it worked, except the bot didnt got online, if you want i can send you a part of my code so you can check

**Comment by Bilal2453** [comment]
Please contact us on our discord server link above. This is not the place for this.
