### ISSUE TITLE
Is possible to detect member's rule screening checks with discordia?

### ISSUE THREAD

**Issue by vico93** [SinisterRectus/Discordia#329]
I was searching for a bot (or code to run one) that allows users that accept [rule screening](https://support.discord.com/hc/pt-br/articles/1500000466882-Rules-Screening-FAQ) to have automatically a role, since in my server we use a basic role for new members.

[Searching](https://www.reddit.com/r/discordapp/comments/khtyop/a_discord_bot_to_add_roles_after_rule_screening/) on [Reddit](https://www.reddit.com/r/discordapp/comments/ki7iq7/give_roles_to_users_at_joining_with_rule/), i found there is an [API verification](https://discord.com/developers/docs/resources/guild#guild-member-object) that is already implemented on [discord.py](https://discordpy.readthedocs.io/en/latest/api.html?highlight=keep%20alive#discord.Member.pending) or discord.js.

Is this already possible with discordia?

**Comment by Bilal2453** [comment]
While the member `pending` property is not officially included, but due to how Discordia internals work you can still access it with `Member._pending`, this should still fire the regular memberJoin event. Giving that, I believe you can indeed implement it in Discordia.

**Comment by vico93** [comment]
Thanks a lot for the clarification!
