### ISSUE TITLE
How do you create a text/voice channel?

### ISSUE THREAD

**Issue by XaoMan** [SinisterRectus/Discordia#336]
I'm trying to make a member logger, with voice channels.

How do I even create a voice/text channel, it seems impossible tbh.

**Comment by Bilal2453** [comment]
Please, redirect your questions to our channel in [Discord API](https://discord.gg/discord-api) server or our [Discordia](https://discord.gg/sinisterware) server.

Issues tab are only for actual issues/suggestions.
