### ISSUE TITLE
how do i use Voice On MacOS(Darwin)

### ISSUE THREAD

**Issue by ImLoadingUuU** [SinisterRectus/Discordia#344]
idk how od i use Voice on MacOS,i installed opus and ... using homebrew.it shows not found

**Comment by ImLoadingUuU** [comment]
If You Has This Error - Please Run Your Terminal as Rosetta
Here is Dylibs!
Opus:
https://cdn.discordapp.com/attachments/939810464794284055/977493008704479262/libopus.dylib
Sodium:
https://cdn.discordapp.com/attachments/939810464794284055/977493008968740934/libsodium.dylib

**Comment by SinisterRectus** [comment]
Hi. By my estimation, there should be no reason why Discordia cannot run on an Apple device (ie, Mac), but I unfortunately cannot guarantee support for it.

I do not own a Mac that I can use for development or testing. I have one for work, but not for personal things, which Discordia is to me. It is also my opinion that Mac is strictly a desktop platform and bots should not run in desktop environments (except for short terms). I strongly recommend investing in a linux server environment, which I can support.

Never the less, you are welcome to join the community at https://discord.gg/sinisterware or https://discord.gg/discord-api and try to get your bot running with community support.
