### ISSUE TITLE
[Question] Retrieving a color for en embed from the message author

### ISSUE THREAD

**Issue by 3Kevi** [SinisterRectus/Discordia#348]
The bot sends an embed, and I want this embed's colour to be the one from the highest role. How can I do it?
 
![image](https://user-images.githubusercontent.com/82259360/173227901-80ade67d-e6b1-45dc-8b89-427b29222921.png)

**Comment by Bilal2453** [comment]
Hi there.

The colors in Discordia are generally represented with numbers. Roles have their color stored in a field called `color`. So all you would have to do is pass `Role.color` to the embed field.

For questions like this, please visit [our Discord](https://discord.gg/sinisterware), or our channel at [Discord API](https://discord.gg/discord-api).

**Comment by 3Kevi** [comment]
Thank you.
