### ISSUE TITLE
 Uncached Message on MESSAGE_REACTION_ADD

### ISSUE THREAD

**Issue by krekeris** [SinisterRectus/Discordia#35]
"reactionAdd " event doesn't get called when someone adds reaction to the message. Only prints following:

Sat Jan  7 22:56:24 2017 - Uncached Message (267425112653824001) on MESSAGE_REACTION_ADD

**Comment by PurgePJ** [comment]
Are you using the `reactionAdd` client even? That printed message looks more like the typical info that's given from time to time due to an uncached element such as messages, users or reactions.

**Comment by krekeris** [comment]
Yeah. It looks like it fails [here](https://github.com/SinisterRectus/Discordia/blob/caf01e5739702cfc5c2f297b6a9e979dabd08e4c/discordia/client/EventHandler.lua#L332) and prints this warning. Here's what I'm trying to do:

```lua
client:on("reactionAdd", function(...)
	print("called")
	print(...)
end)
```

**Comment by SinisterRectus** [comment]
It is not feasible to cache all messages. According to the documentation:

>By default, Discordia will have no cached messages on startup and will only cache the most recent 100 messages per channel as they are received. If you want messages on startup, you can call TextChannel:loadMessages to download 1 to 100 of the most recent messages into the channel's message cache. If you want to store more messages, you can change messageLimit on client initialization.

If a reaction event is received for a message that is not cached, a warning is emitted instead of the expected event. I may eventually add `reactionAddUncached` and `reactionRemoveUncached` events to compensate.

**Comment by krekeris** [comment]
That'd be great.

**Comment by SinisterRectus** [comment]
Commit 3109d0fdc1e366be4653a8fd311f72c9a13d551d includes `reactionAddUncached` and `reactionRemoveUncached` events. These will be featured in the next public release.
