### ISSUE TITLE
bot doesn't respond to commands

### ISSUE THREAD

**Issue by Zordon1337** [SinisterRectus/Discordia#357]
hello I'm beginner at coding bots in lua i have basic !ping command. everything is ok bot is online but when i use !ping nothing happens  no console log, bot doesn't respond

**Comment by Zordon1337** [comment]
But i gonna test it when i will be back in home

**Comment by Zordon1337** [comment]
works thanks and i have another question is there any way to make bot get username of message author and send it
for example if someone gonna say "hello" and bot respond with "hello username_of_message_author"

**Comment by TohruMKDM** [comment]
You can get the username of any user via `user.username`, this is defined in the property table under the Wiki Page for `User` [here](https://github.com/SinisterRectus/Discordia/wiki/User#properties)
So for example you'd do `message.author.username` to get the message author's name.
Also for further inquiries please redirect yourself to either the [DAPI Server](https://discord.gg/discord-api) or the [Discordia Server](https://discord.gg/sinisterware) as Github Issues is intended for reporting bugs and other issues.
