### ISSUE TITLE
Sending a message with embeds

### ISSUE THREAD

**Issue by MuteTM** [SinisterRectus/Discordia#36]
It doesn't appear that I'm currently able to send a message with an embed. This would be highly useful for formatting large messages, as shown by other bots - is this built in and I'm missing it, or is is truly missing?

![Embedding used for text formatting](https://cloud.githubusercontent.com/assets/4689212/21893754/9facbc9c-d899-11e6-9f7e-adf27f3cc673.png)

**Comment by PurgePJ** [comment]
As of today, there is no public function to send Embedded messages. That said, Sinister is working on reworking the sendMessage function.

If you really want to send Embeds and don't want to wait until it is done, you can access the createMessage API function and send a payload including Embeds.

**Comment by MuteTM** [comment]
Thanks for the tip, I'll give it a try.

**Comment by SinisterRectus** [comment]
As of 8f352bf8d22477ab327c7b06bd643d0ceb24941f, Discordia supports more flexible message construction, and can be used to post embeds to a channel. The next public release will contain these changes, and more.
