### ISSUE TITLE
429 - Too Many Requests : GET https://discord.com/api/v7/users/@me

### ISSUE THREAD

**Issue by JaqJoestar** [SinisterRectus/Discordia#360]
When I try to turn on the discord bot it keeps giving me this 
![image](https://user-images.githubusercontent.com/115385108/197902803-a70befac-be6d-408c-9516-e656e72f448a.png)
I have tried searching for help but it doesn't help because my client:run() already has the Bot prefix. If it helps I am doing this on replit so I could host it for free.

**Comment by JaqJoestar** [comment]
I just had to be patient.
Sorry.

**Comment by truemedian** [comment]
For future reference: this error is telling you that you are connecting too quickly. This is quite common on platforms with shared hosting (ie. replit) because you could be fighting for ratelimits with hundreds of other bots.
