### ISSUE TITLE
bot isn't reading message content correctly

### ISSUE THREAD

**Issue by ACAT-0** [SinisterRectus/Discordia#361]
i'm not sure what's happening, but even with the exact code in the wiki tutorial, when i try to check "message.content", it never returns true, even when a message with the exact content tht i'm checking for is sent.

**Comment by ACAT-0** [comment]
after more testing, i've found that any message sent simply returns nothing in the message.content, not even a nil, just nothing.

**Comment by ravener** [comment]
Make sure you enabled the Message Content intent in your bot's settings from the developer portal.

**Comment by ACAT-0** [comment]
oh my god i'm an idiot
