### ISSUE TITLE
Message.content Is Nil For Some Reason!

### ISSUE THREAD

**Issue by xelijah3314x** [SinisterRectus/Discordia#362]
Whenever I Try And See What The Users Message Content Is It's Returning Nil?
Here Is The Code:

```lua
local Discordia = require("../deps/discordia")
local Settings = require("./settings.lua")

local Client = Discordia.Client()

Client:on("ready", function()
    print("Bot Initialized! --" .. Settings["Version"])
end)

Client:on("messageCreate", function(Message)
    if Message then
        local Content = Message.Content
        local IsCommand = string.sub(Content, 1, 1) == Settings["Prefix"]
        local Command = string.sub(Content, 2, string.len(Content))

        print(IsCommand, Command, Content)
    end
end)

Client:run("Bot " .. Settings["Token"])
```

**Comment by xelijah3314x** [comment]
nvm i had to enable it through dev portal

**Comment by SuyfooS** [comment]
> nvm i had to enable it through dev portal

What did you enable ? I have this problem too

**Comment by justdie386** [comment]
Message intent from the discord developer website, also with the new discordia update you’ll have to change your code to add a few intents, check the docs it should show how to enable all of them at once

**Comment by xelijah3314x** [comment]
> > nvm i had to enable it through dev portal
> 
> What did you enable ? I have this problem too

 When you are creating your bot you will see a few options:
 Privileged Gateway Intents
Some [Gateway Intents](https://discord.com/developers/docs/topics/gateway#gateway-intents) require approval if your bot is verified. If your bot is not verified, you can toggle those intents below to access them.

PRESENCE INTENT
Required for your bot to receive [Presence Update](https://discord.com/developers/docs/topics/gateway#presence-update) events.


SERVER MEMBERS INTENT
Required for your bot to receive events listed under [GUILD_MEMBERS](https://discord.com/developers/docs/topics/gateway#list-of-intents).

MESSAGE CONTENT INTENT
Required for your bot to receive [message content](https://support-dev.discord.com/hc/en-us/articles/4404772028055) in most messages.

 You need to check `Message Content Intent`
