### ISSUE TITLE
Discord "Authentication" Error

### ISSUE THREAD

**Issue by Corotyest** [SinisterRectus/Discordia#373]
I have already seen a **similar** problem in another of the "issues", however; mine is a bit different as it involves the `http-codec` module.

In the same way, **I cannot be sure if this is not really my problem**, although on a hosting server this problem occurs in the same way and I have to restart the console since it **does not do it automatically**.

With the aforementioned I can say that the problem in question is "solved" by restarting the task. Well, I will leave here the record that Discordia' makes so that there is a more formidable test.

(The "problem" is almost to the end near 12:00PM or 00:00)
[discordia.log](https://github.com/SinisterRectus/Discordia/files/10714935/discordia.log)

**Comment by truemedian** [comment]
This has been a known issue with http-codec for a bit. There was a fixed committed that never got published to lit. That fix is now in http-codec 3.0.7. You can update by deleting `deps/http-codec.lua` and then running `lit install luvit/http-codec`
