### ISSUE TITLE
[FIX] How to fix other people's messages not showing with selfbots

### ISSUE THREAD

**Issue by multikirin** [SinisterRectus/Discordia#381]
honestly, there are better ways to fix this, but I am too lazy to do it so here's a temporary solution
(this code assumes the actual "message" object is called _message, and the one you'll use is called message)

```lua
        message={}
        message.content=_message.channel:getMessages(1):get(1)
        fakemessage =  {
                __index = function(mytable, key)
                        if _message[key] ~= nil then return _message[key] end
                        if key == "content" then
                                return _message.channel:getMessages(1):get(1)
                        else
                                return mytable[key]
                        end
                end
        }
        message=setmetatable(message,fakemessage)
```

**Comment by truemedian** [comment]
What exactly is this supposed to accomplish? The code is nonsensical and the title of this issue doesn't make any sense.

**Comment by multikirin** [comment]
oops didnt mean to close

**Comment by multikirin** [comment]
another issue is that selfbots cannot create GCs

**Comment by truemedian** [comment]
That code adds the last *message* as the content of the message, not the content of the last message, but regardless selfbots are **NOT** supported. As noted in the issue you've linked, selfbots are against Discord ToS and as such we will not be supporting any use case of them.

**Comment by multikirin** [comment]
> That code adds the last _message_ as the content of the message, not the content of the last message, but regardless selfbots are **NOT** supported. As noted in the issue you've linked, selfbots are against Discord ToS and as such we will not be supporting any use case of them.

now that you said that, it's true, but for some reason it works. Anyways, I'll close this issue
