### ISSUE TITLE
Fresh install fails assertion (`index must be a number if set`) when running Discordia example

### ISSUE THREAD

**Issue by n1tehawk** [SinisterRectus/Discordia#39]
@SinisterRectus We've been discussing and solving this on IRC before. I'm just documenting this here once more for easy reference.

If you try to do a fresh installation of _luvit_ and _Discordia_ following the "Installation" and "Example" steps from the README, you currently might end up with something along the lines of
```
Uncaught Error: mybot/deps/coro-channel.lua:62: mybot/deps/coro-wrapper.lua:109: index must be a number if set
stack traceback:
        [C]: in function 'assert'
        mybot/deps/coro-channel.lua:62: in function 'onPlain'
        ...mybot/deps/secure-socket/biowrap.lua:72: in function <...mybot/deps/secure-socket/biowrap.lua:57>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
```

This is due to the fact that `lit` pulls in dependencies with package versions that are incompatible/broken right now. You can check version numbers by running `lit ls` (in the directory containing the Discord example file, e.g. _mybot_ above). For details, see https://github.com/luvit/lit/issues/200 and https://github.com/luvit/lit/issues/201.

Unfortunately, there is no easy way to request specific (version 'pinned') packages to remedy the situation. The current workaround is to download and an archived version of the `deps/` folder, which will provide you with a working set of dependencies. **Please join the Discord channel** mentioned in the README **and download either _deps.tar.gz_ or _deps.zip_** from the pinned messages.

Regards, NiteHawk

**Comment by SinisterRectus** [comment]
To workaround this issue, I published legacy versions of `coro-http` and `coro-websocket` under my own name. Discordia will rely on these until the underlying Luvit problems are resolved.
