### ISSUE TITLE
bulkDelete is starting to break apart

### ISSUE THREAD

**Issue by hmm-what25** [SinisterRectus/Discordia#390]
So there's a problem where **bulkDelete** doesn't work sometimes it does, sometimes doesn't

This is the error:
![image](https://github.com/SinisterRectus/Discordia/assets/124509925/822b7d02-f776-4152-80e2-a1c5de9fbb95)

before it worked just fine but now it's breaking apart.
I have no idea what's causing it, but it's maybe a Discord update that broke it.

**Comment by Idkkitty** [comment]
i think they broke it with their new update

**Comment by hmm-what25** [comment]
Heres more info:
The channel i'm trying to call bulkDelete on is a guild channel

and this is the source code
![image](https://github.com/SinisterRectus/Discordia/assets/124509925/00c627df-5142-4462-bc25-475caca834e0)

**Comment by Lort533** [comment]
https://github.com/SinisterRectus/Discordia/wiki/GuildTextChannel#bulkdeletemessages
```
Messages over 2 weeks old cannot be deleted and will return an error.
```
If you still think this error is not related to the above statement, you may be able to check the error reason by adding another variable to read the error. Try:
```
local messages = (...)
local response, err = channel:bulkDelete(messages)
p(response, err)
```

**Comment by hmm-what25** [comment]
I can't even delete the latest messages if there are messages over 1 week in the channel

**Comment by hmm-what25** [comment]
Okay, so i added it
The bug was fixed it was maybe a problem in discord's api which they fixed shortly after my post
