### ISSUE TITLE
Discordia Packages Broken

### ISSUE THREAD

**Issue by ojarchives** [SinisterRectus/Discordia#398]
Uh, so basically when ever discoardia loads into vsc, the first error you see is this:

![image](https://github.com/SinisterRectus/Discordia/assets/127899997/6a6a4e7a-abfb-47c9-a293-7cbc5a2ed595)
![image](https://github.com/SinisterRectus/Discordia/assets/127899997/149044af-6163-440c-b959-4cb46c8df3ab)

**Comment by SinisterRectus** [comment]
Discordia runs on Luvit, which uses LuaJIT. Change your Lua version to LuaJIT in VSC.

**Comment by ojarchives** [comment]
Im confused, how do you change the lua version?

**Comment by Ta-noshii** [comment]
Either here:
![image](https://github.com/SinisterRectus/Discordia/assets/79271690/0c3005b4-fb39-428a-8522-d3533f4208e2)
Or it might also automatically change if you enable the Luvit addon (assuming you have the Lua extension by sumneko installed)
![image](https://github.com/SinisterRectus/Discordia/assets/79271690/1f4df744-70d4-4578-9db4-40e04ead1bc2)
by **right-clicking anywhere on your code** at the bottom of the panel that pops up, click `Lua: Open Addon Manager`, install and enable the Luvit addon.
![image](https://github.com/SinisterRectus/Discordia/assets/79271690/15375804-37e0-40be-aa43-25abce4f1b92)
