### ISSUE TITLE
hasRole and addRole not working?

### ISSUE THREAD

**Issue by GithubUser291** [SinisterRectus/Discordia#40]
`111: attempt to call method 'hasRole (a nil value)'`
This error do I keep getting everytime I call hasRole or addRole, does anyone have a solution?

**Comment by Flamanis** [comment]
An error message is not enough to properly diagnose your issue. Showing the code in context allows for an easier time helping. That being said, it's also beneficial to join the Discord API server so that we can assist in as real of time as we can.

**Comment by SinisterRectus** [comment]
`hasRole` is in version 1.4, which I have not yet published to lit. Until then, you can download the master branch if you want to use the extra features, such as `hasRole`.

**Comment by GithubUser291** [comment]
Where can I find the master branch?

**Comment by Flamanis** [comment]
You're on github. The main page of the repo IS the master branch

**Comment by GithubUser291** [comment]
@Flamanis Sorry, this is my first post actually

**Comment by GithubUser291** [comment]
@SinisterRectus Where do I put the master branch when I downloaded it (Sorry, I'm a noob)

**Comment by SinisterRectus** [comment]
You need to move the `discordia` folder from master to the `discordia` folder in your `deps` folder. If you cannot manage this, then please wait for me to update the lit version.

**Comment by GithubUser291** [comment]
Alright I will first try to move discordia :P

**Comment by GithubUser291** [comment]
I just broke my discordia, going to move the old one back D:

**Comment by SinisterRectus** [comment]
Okay. I meant to publish 1.4 last week, so I updated the docs to include all of the new code, but an issue with some of the internal Luvit code made me delay the release. A fix has not been released yet, so I may have to write my own patch into Discordia. When I get this done, I will publish 1.4. Sorry for the confusion.

**Comment by GithubUser291** [comment]
Alright, I'll add addRole to my bot when you release it :P

**Comment by SinisterRectus** [comment]
You can use `addRoles` or `removeRoles`; those already exists. Just use one role object instead of many:
```lua
member:addRoles(role1)
member:addRoles(role1, role2)
```
The `addRole` and `removeRole` functions were added to take advantage of a new Discord endpoint.

If you want `hasRole` code, you can use this:
```lua
local function hasRole(member, role)
	local id1 = role._id
	for _, id2 in ipairs(self._roles) do
		if id1 == id2 then
			return true
		end
	end
	return false
end
```

**Comment by GithubUser291** [comment]
With the addRoles(), do I need the name or the role object?

**Comment by Flamanis** [comment]
As the documentation would speak, I believe it's the object.

**Comment by SinisterRectus** [comment]
1.4.0 is now available on lit.

**Comment by GithubUser291** [comment]
Ok, thank you!
