### ISSUE TITLE
403 - FORBIDDEN

### ISSUE THREAD

**Issue by 0Q1BE** [SinisterRectus/Discordia#402]
Hi, I'm writing an verification bot for my server and after I ended with suffering with code I found new problem "`403 - FORBIDDEN`".
I didn't expect to meet this thing because **I gave my bot administrator permissions**, but even this didn't work.
![image](https://github.com/SinisterRectus/Discordia/assets/153936085/ce9c1c47-cd86-4753-b1a8-dfbf76411886)
![image](https://github.com/SinisterRectus/Discordia/assets/153936085/f0f8d7f7-4adf-45c5-946b-3b715c58b370)
_**What's the matter?**_

**Comment by Bilal2453** [comment]
> If you are getting 403 forbidden  error also know as missing permissions while patching/moderating other members (using methods like :setNickname, :removeRole, :kick), even when your bot does have admin permissions, this might mean the bot's role is 'physically' lower than or equal to the member's role you're trying to patch.
> In this screenshot the Bot role has higher permissions than the Member role, but the member is above Bot, which means when a bot that has Bot role tries to edit (like kicking) a member who have member role, the bot will fail with 403 http error, you can simply fix this by moving up the Bot role, just drag it above the member role, the same problem might happen when a bot tries to patch the server owner member, which can't be done even if its role is higher.

![image](https://github.com/SinisterRectus/Discordia/assets/38175840/c8746d2e-d3b5-4d91-ab24-f146094b819b)

Please for questions like this, you can ask in our [Discord server](https://discord.gg/sinisterware) or at our channel in the Discord API server.

**Comment by 0Q1BE** [comment]
So, in this picture there is a 403 problem (green is role that is adding)
![image](https://github.com/SinisterRectus/Discordia/assets/153936085/f1feb9f9-3961-4357-beae-50841ea3f8ae)
And in this picture there isn't?
![image](https://github.com/SinisterRectus/Discordia/assets/153936085/1c6b372c-03b6-45b0-9e83-368c056f30c2)

**Comment by 0Q1BE** [comment]
And it worked!

**Comment by 0Q1BE** [comment]
thx very much
