### ISSUE TITLE
How to require gateway intents in my code

### ISSUE THREAD

**Issue by bobbibones0** [SinisterRectus/Discordia#406]
I enabled all intents but I still get this error:  | [WARNING] | Cannot cache all members while guildMembers intent is disabled

**Comment by Lort533** [comment]
Code? Hard to tell whether or not you're doing that properly without a code snippet.

**Comment by Ta-noshii** [comment]
Have you enabled the intents in code and on the developer dashboard?

**ps: these type of questions can be asked in our [discord](https://discord.gg/sinisterware)*

**Comment by bobbibones0** [comment]
I was able to fix this, thanks for the replies though
