### ISSUE TITLE
[Question] Custom commnads

### ISSUE THREAD

**Issue by alejandro-alzate** [SinisterRectus/Discordia#433]
I couldn't find if this has been asked before.
But I want to make a custom command with discord's command autocompletion, and so it is listed on the app command menu

Seems that this has to be done on the bot itself and not on the dev portal.

What's the best approach to make the commands?

**Comment by alejandro-alzate** [comment]
most especifically to take advantage of the member list completions.

**Comment by Bilal2453** [comment]
Discordia does not support app commands and therefor does not support auto-completion.

There are community extensions that add said support, join our [Discord server](https://discord.gg/Sinisterware) to learn more information about those extensions.

**Comment by alejandro-alzate** [comment]
Closing as asked on Discord.
