### ISSUE TITLE
Problem with requiring modules

### ISSUE THREAD

**Issue by HuddaFire** [SinisterRectus/Discordia#48]
Are you sure, @SinisterRectus , that there are supposed to be periods when you require something that is in a different directory?

It doesn't fail when I do 'require('/deps/discordia/init')' or dofile('/deps/discordia/init')

However when I do require init, init.lua fails at line 1 (require('./extensions'))

**Comment by Tigerism** [comment]
When using Luvit's require function, the period tells it to start in the current directory. You also need to add a file extension to the require; it's similar to the node require function.

**Comment by ProtectiveManEgg** [comment]
Come join us in the [Discord API server](https://discord.gg/0SBTUU1wZTWVpm07), in #lua_discordia.

**Comment by Flamanis** [comment]
Join us, we will love you forever and ever.

**Comment by HuddaFire** [comment]
Let me screenshot something that says otherwise.

**Comment by HuddaFire** [comment]
https://gyazo.com/6465115aed3d3325ffd5ba00a94039ad

Let me know if you got taken to prank town. 👍

**Comment by HuddaFire** [comment]
Oh no, it's real, Captain.

**Comment by SinisterRectus** [comment]
Luvit has a custom require function that allows for relative POSIX-style paths. The same format can be used in various libuv powered Luvit libraries such as fs and coro-fs. Other Native Lua functions like dofile or loadfile do not benefit from this shortcut.
