### ISSUE TITLE
No such module 'json'

### ISSUE THREAD

**Issue by GithubUser291** [SinisterRectus/Discordia#50]
So as you can see above, whenever I try to launch my bot, I get that error! It worked fine when I was on pc (I'm now using a laptop instead of pc) but now it seems to break and it gives me that error! I have no idea how to fix this  error... Please help me, I want to launch my bot again.

The error occurs on: C:/Users/user/Desktop/Bots/Zap/deps/discordia/client/API.lua'

**Comment by DannehSC** [comment]
Please go download all the luvit deps from the luvit github.
https://github.com/luvit/luvit/tree/master/deps
Luvit has been dumb lately.

**Comment by GithubUser291** [comment]
@DannehSC I'll check it out

**Comment by GithubUser291** [comment]
Sorry, I'm a noob, but where do I put them?

**Comment by DannehSC** [comment]
You may come across additional things that say they don't exist. If it's for example "creationix/coro-fs" then you download https://github.com/creationix/coro-fs
Replace "coro-fs" in the link with whatever you need.

**Comment by DannehSC** [comment]
Also, the deps folder.

**Comment by GithubUser291** [comment]
That is the only error I'm currently rechieving, and the only ""deps" folder I have (that I know I have) is the discordia deps

**Comment by DannehSC** [comment]
Discordia is inside a folder named 'deps'?
If not, create a folder named 'deps' and move your bot.lua to the same directory as the new deps folder.

**Comment by GithubUser291** [comment]
![screenshot_11](https://cloud.githubusercontent.com/assets/25882321/25483793/9bd8e8be-2b57-11e7-9b70-33539233532a.png)

**Comment by DannehSC** [comment]
Ah good. Move everything downloaded to that folder.

**Comment by GithubUser291** [comment]
Ok

**Comment by GithubUser291** [comment]
The deps folder I got right?

**Comment by DannehSC** [comment]
Indeed. The deps folder.

**Comment by GithubUser291** [comment]
Thanks, my bot is online again!
