### ISSUE TITLE
"cannot load module 'libsodium -x86': %1 is not a valid Win32 application."

### ISSUE THREAD

**Issue by KyppuTTo** [SinisterRectus/Discordia#51]
```lua
client.voice:loadOpus('libopus-x86')
client.voice:loadSodium('libsodium-x86')
```
LibSodium from your repository gives this error:
```
c:/luvit/deps/discordia/voice/VoiceManager.lua:28: cannot load module 'libsodium
-x86': %1 is not a valid Win32 application.
```
Maybe replace with last release?

**Comment by Tigerism** [comment]
either you don't have libsodium/libopus installed, or you're not specifying the correct name and path of the file(s)

**Comment by Tigerism** [comment]
I recommend you check out https://github.com/SinisterRectus/Discordia/wiki/Voice

**Comment by KyppuTTo** [comment]
I downloaded latest release of libsodium and its working
