### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by testingroblox-js** [SinisterRectus/Discordia#52]
![image](https://cloud.githubusercontent.com/assets/28508565/25782850/3c7494d8-3352-11e7-8c97-ef4cfcba26c5.png)

**Comment by PurgePJ** [comment]
https://github.com/luvit/luvit/tree/master/deps

Download from there anything you need.

**Comment by SinisterRectus** [comment]
Should be fixed by luvit/luvit#977. Either wait for a new release or download and build from GitHub.

**Comment by SinisterRectus** [comment]
Additionally, you can try `lit make github://luvit/luvit` if you already have lit installed.

**Comment by SinisterRectus** [comment]
Fixed and released with luvit/luvit#980. Run `lit update` or install a fresh copy of luvit.
