### ISSUE TITLE
Bot won't join guilds

### ISSUE THREAD

**Issue by TochigiV** [SinisterRectus/Discordia#54]
Not sure if this problem is just for me or not.

I made a command that makes my bot join a guild using an invite.
![aih](https://user-images.githubusercontent.com/7752021/27157074-e51f74a6-512d-11e7-83bc-ce8f1eeb2523.png)

But when I run the command, the bot doesn't join the guild.
![image](https://user-images.githubusercontent.com/7752021/27156966-6cf74292-512d-11e7-9c6b-c543f9735015.png)

Source:
![image](https://user-images.githubusercontent.com/7752021/27157110-1c9311ea-512e-11e7-8fe0-9533015c15c3.png)

**Comment by Tigerism** [comment]
Bots cannot join guilds through invites -- use oauth2 instead.

**Comment by SinisterRectus** [comment]
https://discordapp.com/developers/docs/topics/oauth2#adding-bots-to-guilds
