### ISSUE TITLE
channel is not seen as a method on windows?

### ISSUE THREAD

**Issue by IanTab1** [SinisterRectus/Discordia#56]
I'm trying to join a voice chat for audio. i am making this for some friends.
i have opus,sodium and ffmpeg.
the bot worked before i tried this.

the error is as follows:

Uncaught Error: C:/Users/Ian/Discordia/deps/coro-channel.lua:62: C:\Users\Ian\Discordia\main.lua:40: attempt to index local 'channel' (a nil value)
stack traceback:
        [C]: in function 'assert'
        C:/Users/Ian/Discordia/deps/coro-channel.lua:62: in function 'dispatch'
        C:/Users/Ian/Discordia/deps/coro-channel.lua:104: in function 'onPlain'
        C:/Users/Ian/Discordia/deps/secure-socket/biowrap.lua:76: in function <C:/Users/Ian/Discordia/deps/secure-socket/biowrap.lua:61>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>

here is my code

local discordia = require('discordia')
local client = discordia.Client()
client.voice:loadOpus('libopus-x64')
client.voice:loadSodium('libsodium-x64')
local pingpong = 0

client:on('ready', function()
	print('Logged in as '.. client.user.username)
	
end)

client:on('messageCreate', function(message)
	if message.content == '!ping' then
		message.channel:sendMessage('Pong!')
	end
	
	if message.content == '!who' then
		message.channel:sendMessage('I am Lewa. a Lua based discord bot')
	end
	
	if message.content == '!help' then
		message.channel:sendMessage('available commands: !ping, !who, !help, !whoami')
	end
	
	if message.content == '!whoami' then
		message.channel:sendMessage('you are'..message.owner.username)
	end
	
	if message.content == '!announce' then
		message.channel:sendMessage('@everyone '..read())
	end

	if message.content == '!serverwhoami' then
		message.channel:sendMessage('you are <invalid>')
	end
	
	if message.content == '!summon' then
		message.channel:sendMessage('attempting to join channel')
		local channel = client:getVoiceChannel('general')
		local connection = channel:join()
	end
end)

client:run(Redacted)

**Comment by Tigerism** [comment]
the channel doesn't exist. provide your code

**Comment by IanTab1** [comment]
local discordia = require('discordia')
local client = discordia.Client()
client.voice:loadOpus('libopus-x64')
client.voice:loadSodium('libsodium-x64')
local pingpong = 0

client:on('ready', function()
	print('Logged in as '.. client.user.username)
	
end)

client:on('messageCreate', function(message)
	if message.content == '!ping' then
		message.channel:sendMessage('Pong!')
	end
	
	if message.content == '!who' then
		message.channel:sendMessage('I am Lewa. a Lua based discord bot')
	end
	
	if message.content == '!help' then
		message.channel:sendMessage('available commands: !ping, !who, !help, !whoami')
	end
	
	if message.content == '!whoami' then
		message.channel:sendMessage('you are'..message.owner.username)
	end
	
	if message.content == '!announce' then
		message.channel:sendMessage('@everyone '..read())
	end

	if message.content == '!serverwhoami' then
		message.channel:sendMessage('you are <invalid>')
	end
	
	if message.content == '!summon' then
		message.channel:sendMessage('attempting to join channel')
		local channel = client:getVoiceChannel('general')
		local connection = channel:join()
	end
end)

client:run('MzM0MDMyNzg0OTgzMDY0NTc4.DEVgOg.LaaKG_QVTFm7FMN90LhAp6IYMbA')

**Comment by Tigerism** [comment]
1.) you should change your token
2.) ``local channel = client:getVoiceChannel('general') `` is wrong.`` you need to either provide an id as the first param, or ("name","general"). you should also call it on a guild.
