### ISSUE TITLE
options for logging

### ISSUE THREAD

**Issue by shadow-absorber** [SinisterRectus/Discordia#57]
make it so you can set the logging mode. for example [info] [debug] [warning] [error] [off]
as this could limit over head and log spam on some systems.

**Comment by PurgePJ** [comment]
iirc Sinister is adding that in Discordia 2.0, this gif is made by him: http://i.imgur.com/SJc32xN.gifv

**Comment by shadow-absorber** [comment]
yeah thanks for the info. this will hopefully stop this madness for my server.


Thu Jul 13 03:58:43 2017 - Uncached User (173993364742471680) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 03:58:45 2017 - Uncached User (173993364742471680) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 03:58:45 2017 - Uncached User (173993364742471680) on MESSAGE_REACTION_REMOVE                                                                        
Thu Jul 13 03:58:46 2017 - Uncached User (173993364742471680) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 03:58:47 2017 - Uncached User (173993364742471680) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 03:58:47 2017 - Uncached User (173993364742471680) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 06:59:32 2017 - Shard 0 disconnected unexpectedly
Thu Jul 13 06:59:32 2017 - Attemping to reconnect after 1000 ms...
Thu Jul 13 10:33:48 2017 - Shard 0 disconnected unexpectedly
Thu Jul 13 10:33:48 2017 - Attemping to reconnect after 1000 ms...
Thu Jul 13 11:12:43 2017 - Uncached User (128195631163375617) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 11:12:43 2017 - Uncached User (128195631163375617) on MESSAGE_REACTION_ADD                                                                           
Thu Jul 13 11:12:44 2017 - Uncached User (128195631163375617) on MESSAGE_REACTION_ADD

**Comment by SinisterRectus** [comment]
2.0 has better, more customizable logging. It should be released within a month.

**Comment by SinisterRectus** [comment]
Discordia 2.0 has been released. It has a custom Logger class that can be used by users, and is also used internally by the Client class for better logging.
