### ISSUE TITLE
updateMessage's message is nil

### ISSUE THREAD

**Issue by SweptThrone** [SinisterRectus/Discordia#61]
If I try to use `message` in the `updateMessage` event, the bot crashes reporting
`attempt to index global 'message' (a nil value)`

Printing `message` within the event will print `nil`.

**Comment by PurgePJ** [comment]
make sure you are running the code this way:

`client:on("messageUpdate", function(message)
 print(message)
end)`

**Comment by SinisterRectus** [comment]
Not enough information / cannot reproduce.
