### ISSUE TITLE
[2.0] Colors not working properly.

### ISSUE THREAD

**Issue by DannehSC** [SinisterRectus/Discordia#62]
Attempting to use `fromRGB(255,0,255)` as a test produced `Lua/deps/discordia/libs/utils/Color.lua:108: bad argument #1 to 'lshift' (number expected, got table)`
Attempting to use `fromHex("#00C8FF")` as a possible alternative to the above produced `Lua/deps/discordia/libs/utils/Color.lua:94: attempt to call method 'match' (a nil value)`
And it appears color values are broken. Creating a class by doing `discordia.Color(255,0,0)` to make red, when printed with `toRGB` prints 0 0 255, the opposite of what it should be.

**Comment by SinisterRectus** [comment]
It's a static method. Don't use `:`.

**Comment by SinisterRectus** [comment]
The two Lua errors are a result of using `class:method` syntax. Static methods are, by nature, meant to be called without reference to a specific class instance, so they are called with `class.method` syntax.

The second issue where `discordia.Color(255,0,0)` returns a color of (0, 0, 255) is a result of you expecting 1.5 behavior in 2.0. The base constructor only accepts one value now, so your code is technically `discordia.Color(255)` where the 255 becomes the less significant byte in `#0000FF`. Use `discordia.Color.fromRGB(255, 0, 0)` instead.
