### ISSUE TITLE
[2.0] Add move member's voice channel

### ISSUE THREAD

**Issue by JohnnyMorganz** [SinisterRectus/Discordia#63]
self explanatory

**Comment by SinisterRectus** [comment]
I could add this now, but 2.0 does not yet handle the `VOICE_STATE_UPDATE` event and there is no useful HTTP data returned when a modify member request is made. This means that you could set voice channels all day long, but the `member.voiceChannel` property will never update beyond its initial state. I will add these features as soon as voice state updates are sufficiently handled.

**Comment by SinisterRectus** [comment]
Implemented with 92082a3fd6b13320dcb6576a5df23771601e5967
