### ISSUE TITLE
[2.0] Remove roles error

### ISSUE THREAD

**Issue by JohnnyMorganz** [SinisterRectus/Discordia#64]
When attempting to remove a member's roles, sometimes the following error occurs:
[Image](https://images-ext-1.discordapp.net/external/KYNweBndiTZkO0QFUmqHpGKTuX43G4SKkQh0Pmwt2Es/https/image.prntscr.com/image/E0HSuz_HTqO8tGqIux5sHA.png?width=516&height=241)

When this happens, the roles do not seem to be removed. (Sometimes they may work though)
Second to this, once the role is removed (and the user has no more roles), the following error occurs:
[Image](https://cdn.discordapp.com/attachments/297714271180029954/351078413043499008/Capture.PNG)

Seeing the member file, and where it occurs, the current action I have in place is commenting out the following piece of code:
`if #roles == 0 then
      self._roles_raw = nil
      self._roles._array = nil
 end`

**Comment by SinisterRectus** [comment]
Should be fixed with 8157e0eeede8031590d148363c49f0bbe3580605. Thanks.
