### ISSUE TITLE
Adding member to role

### ISSUE THREAD

**Issue by Xulua1499** [SinisterRectus/Discordia#66]
Hi,

Having trouble adding a member to a role, current code:

`author:addRoles(352699813684314113)`

I take it I need to pass a role rather than the id, however I was unable to find a way to get all roles etc?

**Comment by EK-W** [comment]
```lua
local role = guild:getRole(roleId)
author:addRole(role);
```

**Comment by PurgePJ** [comment]
Keep in mind that the "author" needs to be a member object

**Comment by Xulua1499** [comment]
Yeah, it's a member object as `author:sendMessage(reply)` works.

Bit lost now, how does one get the "guild". Looks like _parent returns the current members guild, but that doesn't appear to work.

**Comment by EK-W** [comment]
```lua
local guild = author.guild;
```
https://github.com/SinisterRectus/Discordia/wiki/Member#class-properties

**Comment by PurgePJ** [comment]
for guild: client:getGuild("...") or message.guild

> it's a member object as author:sendMessage(reply) works.
that does not mean its a member object, but a user object.

to get the member you can do `message.member`

**Comment by Xulua1499** [comment]
`
local role = guild:getRole(352699813684314113)
member:addRole(role)
`

guild is passed as message.guild and I'm just getting `attempt to index local 'role' (a nil value)`

Printing message.guild comes back with a huge amount of table data.

**Comment by PurgePJ** [comment]
IDs are strings, not numbers.

**Comment by Xulua1499** [comment]
Always the simple things I miss :)

All working, cheers for the help.

**Comment by PurgePJ** [comment]
👍
