### ISSUE TITLE
Audit Log interactions

### ISSUE THREAD

**Issue by Mishio595** [SinisterRectus/Discordia#67]
Will we be seeing methods for pulling information from Discord's audit log? Based on the documentation, there isn't currently any way to pull the objects from it, but the Discord API does support it https://discordapp.com/developers/docs/resources/audit-log

**Comment by SinisterRectus** [comment]
Yes. Audit log support will be the first thing that I add after I release Discordia 2.0.

**Comment by Mishio595** [comment]
Awesome! Looking forward to it.
