### ISSUE TITLE
Bot not logging in

### ISSUE THREAD

**Issue by captain1242** [SinisterRectus/Discordia#68]
So I started with your example script to start understanding Discordia. 

The bot logged on, I stopped the script and now the bot simply doesen't log back in, it is shown as offline but the script says its connected ... I dun know whats wrong.

**Comment by Tigerism** [comment]
If the console says connected, then it's connected to the websocket and it'll be online. 

Are you sure the console isn't showing a cached copy of the stdout messages? Make sure you fully close the terminal, using the force close option on whatever OS you're on, then try running the script again.

**Comment by captain1242** [comment]
Well I test on Winstupid 10, and I closed with Ctrl+C

**Comment by Tigerism** [comment]
I, as well as other Discordia users, have never seen this issue before. It's a problem on your side, not a problem with the library.

**Comment by JohnnyMorganz** [comment]
Sending a screenshot of what the console states will most likely help resolve your problem.

**Comment by captain1242** [comment]
Nothing my dear, the bot starts optimal, I know what lua errors are and how to identify them. And I can assure: No error message or anything is happening on startup.

**Comment by DannehSC** [comment]
Update to 2.0 and add `logLevel=discordia.enums.logLevel.debug` and it'll tell you all the stuff. Side note, in 2.0 you must prefix your token like `Bot <token>`

**Comment by captain1242** [comment]
istn't there a reason that V2 is not the master rep?

**Comment by DannehSC** [comment]
There are no docs, nor voice support, currently. Though it is totally stable. I use it myself.

**Comment by captain1242** [comment]
Alright then, Will check later

**Comment by DannehSC** [comment]
It should be noted that you can learn most of it from the current docs. Anything that seems weird, check the changelog.md in the 2.0 branch.

**Comment by captain1242** [comment]
Nope still not working

**Comment by captain1242** [comment]
```
PS C:\luvit> luvit test.lua
2017-09-06 22:05:53 | [INFO]    | Discordia 2.0.0-indev
2017-09-06 22:05:53 | [INFO]    | Connecting to Discord...
2017-09-06 22:05:53 | [INFO]    | Authenticated as AwesomeBot#5302
2017-09-06 22:05:53 | [INFO]    | Launching shard 0 (1 out of 1)...
2017-09-06 22:05:53 | [INFO]    | Shard 0 : Connected to wss://gateway.discord.gg
2017-09-06 22:05:53 | [INFO]    | Shard 0 : Received HELLO (gateway-prd-main-wkd0)
2017-09-06 22:05:53 | [INFO]    | Shard 0 : Received READY (gateway-prd-main-wkd0, discord-sessions-prd-1-16)
Logged in as AwesomeBot
```
Bot is still offline

**Comment by Tigerism** [comment]
This issue cannot be solved, because it _should_ be online if it connected to Discord. If the bot is offline, then Discord is messing up, which is unlikely. 

This is not a problem with the library.

**Comment by captain1242** [comment]
Is there any Port that needs to be opened?

**Comment by Flamanis** [comment]
If it connected once and fails subsequently, then there are no ports to open. Never was anyways. If your console says 'logged in' then you're logged in. Something else must be the problem. Unless a lot of people encounter the same issue and the only linking factor is Discordia, then it is extremely likely it's Discord's fault or something on your end.

**Comment by DannehSC** [comment]
Hit ctrl+r on your discord window. Sometimes a refresh fixes errors of presence changes.

**Comment by SinisterRectus** [comment]
Can you show a screenshot of the console running the bot with the member list of your Discord client where the bot is shown as "offline"?

**Comment by captain1242** [comment]
https://www.pic-upload.de/view-33876518/Screenshot215.png.html

**Comment by SinisterRectus** [comment]
Are you setting the status to invisible?

**Comment by captain1242** [comment]
I am not setting a status at all, also if it would just be invisible, wouldn't it still respond to commands?

**Comment by Tigerism** [comment]
The first few messages in the screenshot show it responding. If it's responding, then it'll be online, unless you are changing the status of it.

**Comment by captain1242** [comment]
It was online like I said, I restarted and now its not working anymore, like i said

**Comment by SinisterRectus** [comment]
It should, but you never said it was not. I've never seen this happen before, so I don't know what's wrong. Are you sure you don't have two different AwesomeBots?

**Comment by captain1242** [comment]
Yes I am sure

**Comment by DannehSC** [comment]
Did you enable debug in client options like I said earlier? `logLevel=discordia.enums.logLevel.debug`

**Comment by captain1242** [comment]
... found it ... Discord messed up .. my bot got a new user and thats why the old one didn't work ... thanks for the help tho ..
