### ISSUE TITLE
[2.0] NSFW Channels do not update

### ISSUE THREAD

**Issue by JohnnyMorganz** [SinisterRectus/Discordia#69]
As the current way to update a channels NSFW status is by toggling in the channel settings, Discordia does not take into account an NSFW change through channel settings whilst the bot is running.

If a channel is set to NSFW at the time of the channel being cached, it will have `nsfw` set to `true`, if not, it will be `false`.

If a user makes a new channel, and makes it NSFW (or edits a current channel that is not NSFW), the `nsfw` property will not be changed.

**Comment by SinisterRectus** [comment]
Cannot reproduce. Please provide a minimal sample of code that reproduces the issue.

**Comment by SinisterRectus** [comment]
Any info on this? Are you making the channel NSFW by setting it in the client, directly via the API, or are you just putting "nsfw" in the name?

**Comment by JohnnyMorganz** [comment]
Yeah, uh, I removed NSFW features from my bot.
I did see it multiple times, I might reproduce it later if need be.
Can close if you want
