### ISSUE TITLE
On failed reconnect attempt, discordia errors

### ISSUE THREAD

**Issue by sclark39** [SinisterRectus/Discordia#7]
When returning from sleep mode, the bot was obviously disconnected. When trying to reconnect, it failed, and so `websocket.write` was still nil, but it tried to call it anyways in `websocket.resume`.

It appears that the reconnect system assumes that it will be successful on the first reconnect.

----------------
WebSocket disconnected while logged in. Reconnecting in 5 seconds.
stack traceback:
        ...rs/Sky/Desktop/discordia/luvit/deps/discordia/client.lua:228: in function <...rs/Sky/Desk
top/discordia/luvit/deps/discordia/client.lua:204>

Uncaught exception:
...top/discordia/luvit/deps/discordia/classes/websocket.lua:23: attempt to call field 'write' (a nil
 value)
stack traceback:
        [builtin#2]: at 0x013894f0
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>```

**Comment by SinisterRectus** [comment]
Should be handled after 282c392c95bd4b8eb7a7d12aa0d5a291767015ad. Not much I can do to overcome a failed connection, and there's no point in spamming a bad gateway, so this situation will output a known error message and terminate the program.
