### ISSUE TITLE
Using Discordia without luvit

### ISSUE THREAD

**Issue by captain1242** [SinisterRectus/Discordia#74]
So, 
I have installed modules for lua with luarocks and now afterwards it seems that the lib I am using for discord is broken, so I came back to discordia. Now my problem is, I installed modules ( such as luasql ) which I need for what I am doing, So is there any way that I can use discordia with the regular lua interpreter, or that you make it somehow compatible to luarocks ?

thanks for reading,
~cap

**Comment by DannehSC** [comment]
I do not believe Sinister will officially support luarocks due to the differences between luvit and luarocks. Luvit has most of the needed dependancies available at stock. You could attempt to modify 2.0's source to fit luarocks, but that nullifies most support requests.

**Comment by captain1242** [comment]
Without luaSQL this lib is useless for what I am doing

**Comment by SinisterRectus** [comment]
Discordia only runs on Luvit, sorry. You may be able to run LuaSQL, or other SQL libraries, on Luvit.

**Comment by captain1242** [comment]
I might have found one, but I don't understand exactly how luvit works, so how do I install this: https://github.com/kengonakajima/luvit-mysql ?

**Comment by Nik-mmzd** [comment]
As I remember, luarocks is just package manager, so try to use LuaSQL with luvit 🤷‍♂️

**Comment by captain1242** [comment]
No, LuaRocks compiles the into lua. Means you download the package and it installs it so you can use them with your lua interpreter. 

and when I try to use it with luvit "[string "bundle:deps/require.lua"]:279: No such module 'luasql.mysql' in '/lua/test.lua'"

**Comment by SinisterRectus** [comment]
Show the code that you are using to require the module.

**Comment by captain1242** [comment]
```require("luasql.mysql")```

**Comment by SinisterRectus** [comment]
You need to either put the module in a location where the require function can find it, or pass a useful path to the require function. It won't magically find the module if it's not in one of the locations that it expects it to be. Note that Luvit uses a custom require that can handle relative paths, so you can try the same directory as your Lua script and use `require("./moduleName")`.

**Comment by captain1242** [comment]
wonderfull... a lot of search has to be done to find the place where it put the mysql.so file

**Comment by captain1242** [comment]
Doesen't work
```
Uncaught exception:
[string "bundle:deps/require.lua"]:323: /usr/local/lib/lua/5.3/luasql/mysql.so#luaopen_mysql: /usr/local/lib/lua/5.3/luasql/mysql.so: undefined symbol: luaL_setfuncs
stack traceback:
        [C]: in function 'error'
        [string "bundle:deps/require.lua"]:323: in function 'require'
        ...www/clients/client1/web3/home/rainbowsteam/test/test.lua:2: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function 'require'
        [string "bundle:main.lua"]:118: in function 'main'
        [string "bundle:init.lua"]:49: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```

**Comment by SinisterRectus** [comment]
For future reference, `luarocks show luasql-mysqlite` tells you where it is installed.

Looks like it won't load, though. This might be a LuaJIT compatibility issue.

I don't know how to install the Luvit MySQL module. There is a Makefile, though, if you can decipher that.

If you want to use SQLite, I can recommend several different modules for that.

**Comment by captain1242** [comment]
I need MySQL not SQLite

**Comment by SinisterRectus** [comment]
If you want to try the Luvit version that you linked above, you can just copy the repository to a folder and require the `mysql.lua` file. It's all Lua, so there is no C module that needs to be compiled.

**Comment by Mishio595** [comment]
I successfully use luasql.postgresql installed via luarocks with my bot. 
```lua
local luasql = require'luasql.postgres`
local env = luasql.postgres()
```
From there its just opening a connection and executing commands. The point is that it works just fine as long as the luasql module is installed either locally or within the global lua path.

**Comment by SinisterRectus** [comment]
Great!

**Comment by SinisterRectus** [comment]
There is also a Luvit module that uses coroutines for asynchronous communication. https://github.com/creationix/lua-postgres

It requirew old dependencies that should be updated before anyone uses it seriously, though. Use what works for you.

**Comment by captain1242** [comment]
@Mishio595 
```root@server /lua # ./luvit proof.lua
Uncaught exception:
[string "bundle:deps/require.lua"]:279: No such module 'luasql.mysql' in '/lua/proof.lua'
module 'luasql.mysql' not found:
        no field package.preload['luasql.mysql']
        no file './luasql/mysql.lua'
        no file '/usr/local/share/luajit-2.1.0-beta2/luasql/mysql.lua'
        no file '/usr/local/share/lua/5.1/luasql/mysql.lua'
        no file '/usr/local/share/lua/5.1/luasql/mysql/init.lua'
        no file './luasql/mysql.so'
        no file '/usr/local/lib/lua/5.1/luasql/mysql.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './luasql.so'
        no file '/usr/local/lib/lua/5.1/luasql.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        [string "bundle:deps/require.lua"]:279: in function 'require'
        /lua/proof.lua:1: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function 'require'
        [string "bundle:main.lua"]:118: in function 'main'
        [string "bundle:init.lua"]:49: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```
Also is what you sent in an copy and paste of your code?

**Comment by SinisterRectus** [comment]
What MySQL package is needed to install luasql-mysql? I'd like to see if I can get it to work.

**Comment by captain1242** [comment]
The MySQL development tools. 
```libmysqlcppconn-dev```
I think this is it, not sure tbh
but it should have a folder at: /usr/include/mysql

**Comment by SinisterRectus** [comment]
Okay, I installed it with `luarocks install luasql-mysql`:

```
sinister@ubuntu:~$ luarocks show luasql-mysql

LuaSQL-MySQL 2.3.5-1 - Database connectivity for Lua (MySQL driver)

LuaSQL is a simple interface from Lua to a DBMS. It enables a Lua program to
connect to databases, execute arbitrary SQL statements and retrieve results in
a row-by-row cursor fashion.

License:        MIT/X11
Homepage:       http://www.keplerproject.org/luasql/
Installed in:   /usr/local

Modules:
        luasql.mysql (/usr/local/lib/lua/5.1/luasql/mysql.so)
```

Lua:
```
sinister@ubuntu:~$ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> for k, v in pairs(require('luasql.mysql')) do print(k, v) end
mysql   function: 0x118a3e0
_COPYRIGHT      Copyright (C) 2003-2017 Kepler Project
_CLIENTVERSION  5.7.19
_DESCRIPTION    LuaSQL is a simple interface from Lua to a DBMS
_VERSION        LuaSQL 2.3.5 (for Lua 5.1)
```

LuaJIT:
```
sinister@ubuntu:~$ luajit
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> for k, v in pairs(require('luasql.mysql')) do print(k, v) end
_COPYRIGHT      Copyright (C) 2003-2017 Kepler Project
_VERSION        LuaSQL 2.3.5 (for Lua 5.1)
_DESCRIPTION    LuaSQL is a simple interface from Lua to a DBMS
_CLIENTVERSION  5.7.19
mysql   function: 0x40ba59c8
```

Luvit:
```
sinister@ubuntu:~$ luvit
Welcome to the Luvit repl!
> for k, v in pairs(require('luasql.mysql')) do print(k, v) end
_COPYRIGHT      Copyright (C) 2003-2017 Kepler Project
_VERSION        LuaSQL 2.3.5 (for Lua 5.1)
_DESCRIPTION    LuaSQL is a simple interface from Lua to a DBMS
_CLIENTVERSION  5.7.19
mysql   function: 0x41d47df0
```

Works in all three for me.

```

**Comment by captain1242** [comment]
You actually have lua 5.1 while I have 5.3, that might be the issue <.<

**Comment by SinisterRectus** [comment]
Oh. There is a strong change that this is the issue. I just used the standard Luarocks installation, which uses 5.1 by default. Luvit uses LuaJIT, which is API and ABI compatible with Lua 5.1.

**Comment by captain1242** [comment]
So I installed lua 5.1 but all the stuff like lua.h is missing, what package am I missing?

**Comment by SinisterRectus** [comment]
Luarocks should install what it needs, This us the ubuntu package that I installed https://packages.ubuntu.com/xenial/luarocks

**Comment by captain1242** [comment]
Missing dependencies for cqueues 20161215.53-0:
   lua == 5.3 (5.1-1 provided by VM)
Missing dependencies for http 0.2-0:
   bit32 (not installed)

I get this error when I try to install it.

**Comment by SinisterRectus** [comment]
As far as I know, those aren't dependencies for LuaSQL. I don't know what is wrong there. You're going to have to ask either the Luarocks people or the LuaSQL people how to get a 5.1 installation working.

**Comment by captain1242** [comment]
luarocks is still installed with lua5.3 ( i installed it mannually ) and now I don't know how to remove it from my system.

**Comment by SinisterRectus** [comment]
I'm not Linux support either. Try:

`sudo apt autoremove lua5.3`
`sudo apt autoremove luarocks`
`sudo apt install luarocks`
`sudo luarocks install luasql-mysql`

**Comment by SinisterRectus** [comment]
If you installed it manually, then you have to uninstall it manually.

**Comment by Mishio595** [comment]
Oh, I did forget to mention, I'm running archlinux and I had to use luarocks51 instead of basic luarocks, which uses lua 5.3. If I know what distrobution you're using, I can offer installation help.

@captain1242

**Comment by captain1242** [comment]
ok, I found a solution and it works now, thanks for all the help :D

**Comment by Obaidah-Jbreel** [comment]
i know that's old but i want to create a discord bot with lua and i want to use mysql and i have searching for i while and id didn't find smth that i could use until i saw you could you tell my what's the solution that you got ?

**Comment by ApertureDevelopment** [comment]
> i know that's old but i want to create a discord bot with lua and i want to use mysql and i have searching for i while and id didn't find smth that i could use until i saw you could you tell my what's the solution that you got ?

Oh yeah sure, sorry for not having it posted here XD

Basically Luvit uses the Lua Engine that is already avaiable on the system, and LuaRocks modified that default engine. So in conclusion, any LuaRocks package you install will also be avaiable in Luvit/Discordia.

But another solution would be to re-consider and use Postgresql, there actually is a Luvit plugin for Postgres ( the SQL syntax is almost the same, so you don't will have to re-learn a new database ) 

https://luvit.io/lit.html#sql
here you can find a list of avaiable database packages for Luvit. There may also exist some packages that are not listed there, but the list should help you ^^

**Comment by Obaidah-Jbreel** [comment]
> > i know that's old but i want to create a discord bot with lua and i want to use mysql and i have searching for i while and id didn't find smth that i could use until i saw you could you tell my what's the solution that you got ?
> 
> Oh yeah sure, sorry for not having it posted here XD
> 
> Basically Luvit uses the Lua Engine that is already avaiable on the system, and LuaRocks modified that default engine. So in conclusion, any LuaRocks package you install will also be avaiable in Luvit/Discordia.
> 
> But another solution would be to re-consider and use Postgresql, there actually is a Luvit plugin for Postgres ( the SQL syntax is almost the same, so you don't will have to re-learn a new database )
> 
> https://luvit.io/lit.html#sql
> here you can find a list of avaiable database packages for Luvit. There may also exist some packages that are not listed there, but the list should help you ^^

does sqlite3 support mysql database ? because i know this one but i want t oconnect with mysql database

**Comment by ApertureDevelopment** [comment]
No it does not. SQLite is a database file format, meaning its a local database file. But the two other ways should also be considered by you. Postgresql is almost the same as MySQL and there are Luvit plugins for postgresql. Or use the MySQL package for LuaRocks

**Comment by Obaidah-Jbreel** [comment]
> No it does not. SQLite is a database file format, meaning its a local database file. But the two other ways should also be considered by you. Postgresql is almost the same as MySQL and there are Luvit plugins for postgresql. Or use the MySQL package for LuaRocks

can i have your discord because i see that you have a good experience at lua and i need help about that because i want create my own bot at discord by luvit and i want to use mysql database to make it powerful bot like other famous bots that use another programming language . 
sorry about that bad grammar

**Comment by Bilal2453** [comment]
Mysql does not make your bot more "powerful", in fact, Mysql should be the last database you want to use.

Please for further questions and explanations visit [Discordia server](https://discord.gg/EzRYYDW) or Discodia channel at [Discord API](https://discord.gg/discord-api) server.

**Comment by Obaidah-Jbreel** [comment]
> Mysql does not make your bot more "powerful", in fact, Mysql should be the last database you want to use.
> 
> Please for further questions and explanations visit [Discordia server](https://discord.gg/EzRYYDW) or Discodia channel at [Discord API](https://discord.gg/discord-api) server. This is not the right place for these questions.

i didn't mean that mysql is going to make it a powerful one , i can make it a powerful bot with good features for that i need mysql to make an advanced website that can change client settings Instead of using a lot of commands . thanks for the discord link
