### ISSUE TITLE
Question for guild roles

### ISSUE THREAD

**Issue by captain1242** [SinisterRectus/Discordia#75]
I am trying to get all roles from a specific guild and look for the id of the role "test" ( as example ). How do I get the roles of a guild to an array, which I can search trough?

**Comment by Tigerism** [comment]
1.5:
for role in guild.roles do
  print(role.name,role.id)
end

2.0:
for role in guild.roles:iter() do
  print(role.name,role.id)
end

instead of opening issues for questions, ask in discord.gg/discord-api and search for #lua_discordia

**Comment by captain1242** [comment]
oh, didn't know this exists <.< ty
