### ISSUE TITLE
Error while trying to use setGame or setStatus

### ISSUE THREAD

**Issue by captain1242** [SinisterRectus/Discordia#76]
I get this error if I try to use setGame: 
```
Uncaught Error: /lua/deps/coro-channel.lua:62: /lua/deps/discordia/utils/Emitter.lua:62: /lua/bot.lua:71: attempt to call method 'setGame' (a nil value)
stack traceback:
        [C]: in function 'assert'
        /lua/deps/coro-channel.lua:62: in function 'dispatch'
        /lua/deps/coro-channel.lua:104: in function 'onPlain'
        /lua/deps/secure-socket/biowrap.lua:76: in function </lua/deps/secure-socket/biowrap.lua:61>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```
The client starts up normally. Just when I try to use those function it instantly crashes.

This is how I do it:
 ```
client:on('ready',function()
	client:setGame("Test")
end)```

**Comment by DannehSC** [comment]
Why don't you come join discord api at discord.gg/discord-api and ask in #lua_discordia ?

**Comment by captain1242** [comment]
cause always when I am on developer discords, other developers are just shouting "LOL U STUPID" just cause they learned it and you didn't yet. I hate those insults which makes absolutely no sense.

"Oh you are a beginner, so you are a stupid idiot." is the typical logic, and I hate that.

I remember when I publicated my first GMod addon ... getting insulted for not doing it on their way was not a nice experience ...

**Comment by Tigerism** [comment]
You're probably not on Discordia 2.0. I would recommend installing Discordia on a new deps folder and moving the relevant files over to your deps folder, to avoid conflicts.

**Comment by DannehSC** [comment]
Well in the discordia channel, most of the developers are friendly and don't mind helping newer people. There are some who are an asshole (FLAMANIS) but don't mean it like they're being hateful.

**Comment by Tigerism** [comment]
The lua_discordia channel is for quick, immediate help. We don't treat people like that, but it might benefit you to join to get more sufficient help for issues.

**Comment by captain1242** [comment]
am I required to have Discordia 2.0 in order to use those functions? I mean they are clearly defined in the current master branch

**Comment by DannehSC** [comment]
The new current master branch *IS* 2.0. Sinister just updated it, as well as the incomplete docs.

**Comment by SinisterRectus** [comment]
Discordia 1.5 has `setGameName`. Discordia 2.0 has `setGame`.

**Comment by captain1242** [comment]
seems to not do anything ... it doesen't throw an error this time but it didn't set the bots game.

also then, can I simply replace the deps folder with the new one? How do I properly update?

**Comment by DannehSC** [comment]
Delete your deps folder and reinstall anything that isn't pre-installed by 2.0 of discordia.

**Comment by SinisterRectus** [comment]
You should install a new copy of Discordia to a new directory to be safe. You don't have to delete an old copy unless you want to replace it entirely.

**Comment by captain1242** [comment]
so delete it and again run the lit install ?

**Comment by captain1242** [comment]
Well I would replace it entirely

**Comment by SinisterRectus** [comment]
Then do it however you wish, but I recommend just making a new directory.

**Comment by captain1242** [comment]
wasn't there now something special i need to do with my token? I forgot what i need to do now

**Comment by DannehSC** [comment]
```Lua
client:run('Bot '..token)
```

**Comment by SinisterRectus** [comment]
Also, regarding the people that are insulting new users. You're welcome to join us in the Lua channel. We're usually more welcoming to new users than the general population. If anyone harasses you, you can report them to me.

**Comment by SinisterRectus** [comment]
Issue was due to a `io.read` call, which blocks the main loop. The asynchronous `process.stdin:on('data', fn)` should be used instead.
