### ISSUE TITLE
Too many members

### ISSUE THREAD

**Issue by SinisterRectus** [SinisterRectus/Discordia#78]
If a member leaves a guild, its object is uncached normally. After this, a presence update can come in that signifies that the member's status has changed to offline. If the client has `cacheAllMembers` enabled, the presence update will add a new member to the guild. The guild's cache will then have more members than it should. This becomes a critical issue when a member leaves a guild while member chunks are still being received. Unfortunately, there is no straightforward way to distinguish between members that have left the guild, members that are actually going offline, and members that are switching to invisible.

**Comment by jo0sh** [comment]
Oh

**Comment by jo0sh** [comment]
When will this be fixed

**Comment by SinisterRectus** [comment]
As soon as I find the time to fix it.

**Comment by SinisterRectus** [comment]
Issue still exists. Will have to re-write presence handling some time soon.

**Comment by trumpCoder** [comment]
Uhh, then if I get this "too many members" error, does that mean this library doesn't support large servers?

**Comment by trumpCoder** [comment]
This must be fixed ASAP.

**Comment by SinisterRectus** [comment]
The issue should be fixed as of b286af2f2d34988402d4664692e08a37a6e79527. I'm not sure when I'll be able to publish a release to lit, but you're free to use the GitHub version instead.

**Comment by SinisterRectus** [comment]
Released in version 2.3.0.
