### ISSUE TITLE
Error when there is @everyone or @here in message

### ISSUE THREAD

**Issue by Nik-mmzd** [SinisterRectus/Discordia#8]
Error when there is a @everyone or @here mention in received message
Stacktrace:

> Uncaught Error: [string "/home/pi/bin/deps/coro-channel.lua"]:62: [string "/home/pi/bin/deps/discordia/classes/discord/m..."]:42: attempt to index global 'server' (a nil value)
> stack traceback:
>         [C]: in function 'assert'
>         [string "/home/pi/bin/deps/coro-channel.lua"]:62: in function 'dispatch'
>         [string "/home/pi/bin/deps/coro-channel.lua"]:100: in function 'onPlain'
>         [string "/home/pi/bin/deps/secure-socket/biowrap.lua"]:72: in function <[string "/home/pi/bin/deps/secure-socket/biowrap.lua"]:57>
>         [C]: in function 'run'
>         [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
>         [C]: in function 'xpcall'
>         [string "bundle:init.lua"]:47: in function 'fn'
>         [string "bundle:deps/require.lua"]:300: in function <[string "bundle:deps/require.lua"]:265>

**Comment by SinisterRectus** [comment]
Cannot reproduce. Please provide the code that produces this error.

**Comment by Nik-mmzd** [comment]
@SinisterRectus 
I can [provide](https://pastebin.com/kgkGQ6uv) my not the best code, I hope it is not my mistake

**Comment by SinisterRectus** [comment]
I can't reproduce it with that code either. Run `lit ls` and make sure your library is v0.4.5. Also make sure luvit is v2.11.0 by running `lit update`.

**Comment by Nik-mmzd** [comment]
@SinisterRectus 
library was 0.4.5, but when i reinstalled it, all will be OK. Thanks for help
