### ISSUE TITLE
Get user id by user's fullname

### ISSUE THREAD

**Issue by Dakraid** [SinisterRectus/Discordia#81]
Greetings,
this is more of a feature request than an issue, but I think it might be a good feature to have.

What I'm asking for is a function to get the user id through the user's fullname. 
The fullname is normally easier to obtain than the id, as it doesn't require mentioning someone within a channel, and is somewhat easier to understand, since the fullname is not hidden unlike the id. From there on it can be used for the other functions like getMember, making it easier to handle administrative commands implemented within a bot for example.

Not sure if it is easily doable and I'm just not seeing it or it does require more work than I hope it would.

Thank you for your effort and have a nice day,
Dakraid

**Comment by EK-W** [comment]
When you say full name, do you mean their username and their discriminator? Or just their username? Or their guild-specific nickname?

**Comment by SinisterRectus** [comment]
It's not possible to do this through the Discord API, but if a user happens to be already cached, you can find the object in Discordia with a call to the appropriately named method:

```lua
local user = client.users:find(function(u) return u.fullname== "SinisterRectus#2219" end)
```

**Comment by Dakraid** [comment]
It has been recently pointed out to be that Discord indeed has an easy way to access the IDs through the context menu. I honestly cannot believe that all this time I haven't seen that. That makes the request kinda obsolete, since there is no difference between just copying the ID through the context menu or copying the fullname.

Sorry for this oversight of mine.
