### ISSUE TITLE
How do you make lit upgrade to the most recent version of Discordia?

### ISSUE THREAD

**Issue by Flairieve** [SinisterRectus/Discordia#82]
I'm having issues trying to update Discordia to the most recent version, and I was wondering how do you update Discordia to the recent commit with using lit because it will only install an older version of Discordia if I used the normal command. Any help?

**Comment by SinisterRectus** [comment]
You need to install it to a fresh directory OR remove the old version and its dependencies and install the new one. Lit does not have any auto-updating, unfortunately.

**Comment by Flairieve** [comment]
Once I updated Discordia apparently it complains how it can no longer authenticate and that 401 is unauthorized?

**Comment by SinisterRectus** [comment]
Don't assume that your code will work the same for a major update. Read the changelog for version 2.0.0, especially where it says that bot tokens must be prefixed.

**Comment by Flairieve** [comment]
Thank you, it now works correctly!
