### ISSUE TITLE
Is it possible to send messages to a channel outside of a callback?

### ISSUE THREAD

**Issue by zpetty33** [SinisterRectus/Discordia#83]
I would like to be able to send a message to a specific channel outside of the messageCreate callback. For example, having a timer that sends a message every hour or so. Is this possible?

I've noticed that if I try to do something like: client:getGuild('1234567890'):getChannel('1234567890'):send("AHHH")

this would work inside of the messageCreate callback, but not if I tried running it inside of a separate function outside of the callback function.

Is there a way to do this?
Thanks! :)

**Comment by Ale32bit** [comment]
You can use coroutine.wrap

```lua
coroutine.wrap(function()
  --code here
end)()
```

**Comment by Tigerism** [comment]
You can use a separate function to send a message.

```lua
local function sendMessage(guild)
  guild:getTextChannel("1234"):send("hello")
end

client:on("messageCreate",function(message)
  sendMessage(message.guild)
end

```

There's the ``timer`` module which you could require which can be used in the sendMessage example function.

**Comment by zpetty33** [comment]
Thank you everyone for your help! I was able to get some assistance last night on the discord channel. What I didn't understand was that Discordia required all actions to be within the coroutine. coroutine.wrap is what I used to allow for my messages to send properly.
