### ISSUE TITLE
meme

### ISSUE THREAD

**Issue by MrJacz** [SinisterRectus/Discordia#84]

**Comment by Mstrodl** [comment]
delet this

**Comment by lorpus** [comment]
yes

**Comment by MrJacz** [comment]
sure

**Comment by PurgePJ** [comment]
Please don't start doing this. Thank you.

**Comment by Mstrodl** [comment]
Oh hey look we can talk in the channel with this 👀

**Comment by lorpus** [comment]
You're welcome!

**Comment by kev1ns** [comment]
whoops finger slipped accidentally deleted discord api

**Comment by Pandentia** [comment]
Don't abuse GitHub for this.

**Comment by Mstrodl** [comment]
rip webhook

**Comment by MrJacz** [comment]
how to talk in channels 101

**Comment by xXBuilderBXx** [comment]
https://weeb.hacked-your.webcam/20c0217.png the modbot that deleted the channels

**Comment by ArtutoGamer** [comment]
Indeed

**Comment by Mstrodl** [comment]
To be fair, you have to have a very high IQ to understand Discord API. The humour is extremely subtle, and without a solid grasp of horse dildos most of the jokes will go over a typical Discord.NET programmer's head. There’s also Danny's nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they’re not just funny- they say something deep about LIFE. As a consequence people who dislike Discord API truly ARE idiots- of course they wouldn’t appreciate, for instance, the humour in Danny's existential catchphrase “!ban” which itself is a cryptic reference to Turgenev’s Russian epic Fathers and Sons. I’m smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Danny's genius wit unfolds itself on their computer monitors. What fools.. how I pity them. :joy:

And yes, by the way, i DO have a Bad Dragon tattoo. And no, you cannot see it. It’s for the ladies’ eyes only- and even then they have to demonstrate that they’re within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid :sunglasses:
