### ISSUE TITLE
Previous heartbeat not acknowledged

### ISSUE THREAD

**Issue by GalacticAlliance** [SinisterRectus/Discordia#87]
I keep getting this, the bot will work for a few hours then through that warning and switch off.

https://gyazo.com/9fa7ae3bb846acd7230c71093d999994

**Comment by DannehSC** [comment]
have you tried downloading more internet speed lol

**Comment by SinisterRectus** [comment]
Missing and handling a heartbeat id normal behavior for the library. I can't do anything else unless you provide code that reproduces the error.
