### ISSUE TITLE
Bot stops when it calls message.server:getBannedUsers() but have no permission to view banned users

### ISSUE THREAD

**Issue by Nik-mmzd** [SinisterRectus/Discordia#9]
Crash on message.server:getBannedUsers() when there is no permission
I think, it should return nil, but it should not stop bot.

Stacktrace:
> 403 / Forbidden request attempted. Check client permissions.
> stack traceback:
>         /home/pi/bin/deps/discordia/client.lua:133: in function 'request'
>         /home/pi/bin/deps/discordia/classes/discord/server.lua:141: in function 'getBannedUsers'
>         /home/pi/bin/bot.lua:320: in function 'handler'
>         [string "bundle:deps/core.lua"]:248: in function <[string "bundle:deps/core.lua"]:235>

lit ls:
> lit version: 3.3.3
> luvi version: v2.7.2
> command: ls
> SinisterRectus/discordia    v0.4.5   
> creationix/base64           v2.0.0   
> creationix/coro-channel     v2.2.0   
> creationix/coro-http        v2.1.1   
> creationix/coro-net         v2.2.0   
> creationix/coro-websocket   v1.0.0-1 
> creationix/md5              v1.0.2-1 
> creationix/pathjoin         v2.0.0   
> creationix/sha1             v1.0.2   
> creationix/websocket-codec  v2.2.1   
> luvit/http-codec            v2.0.0   
> luvit/resource              v2.1.0   
> luvit/secure-socket         v1.1.3   
> done: success

Code:
```
local banlist = message.server:getBannedUsers()
if banlist == nil then p("No access to banlist");return end --here I get this error, and bot stops
```
Maybe I did something wrong?

**Comment by SinisterRectus** [comment]
That is not an uncaught exception. It outputs an error because your account does not have permission to access bans, but it should not terminate the program. Please check again and confirm that the "bot stops".

**Comment by Nik-mmzd** [comment]
@SinisterRectus I checked before I wrote here.
Bot stops without any other stacktrace.

```
client:on('messageCreate', function(userCMD)
-- there was some code
cmdPrev[userCMD.server.id][userCMD.author.id] = userCMD.content
      local banned = 0
      local answer = {}
      local banlist = userCMD.server:getBannedUsers() -- there all stops
      if banlist == nil then p("No access to banlist");return end
      for _,v in pairs(banlist) do
        table.insert(answer, "**"..v.username.."** (ID: "..v.id..")")
        banned = banned +1
      end
      bigMessage(answer, userCMD.channel, "<@"..userCMD.author.id..">, в бане сидят "..banned.." человек:\n")
```
But I'll check all another time, and I'll try to find a solution

**Comment by Nik-mmzd** [comment]
I added
`p("after-getBanned")`
after
`local banlist = userCMD.server:getBannedUsers()`
So, nothing changed - code execution stops at line
`local banlist = userCMD.server:getBannedUsers()`
I mean, next string (`p("after-getBanned")`) wasn't executed

**Comment by SinisterRectus** [comment]
I think you posted the red-highlighted trace, which is a caught exception, but did not include the uncaught exception. Is there anything else printed after `[string "bundle:deps/core.lua"]:248: in function <[string "bundle:deps/core.lua"]:235>`?

**Comment by Nik-mmzd** [comment]
@SinisterRectus ¯\_(ツ)_/¯
![image](https://cloud.githubusercontent.com/assets/19509291/15457048/c6c7a516-208a-11e6-8a01-755db85a84c4.png)

**Comment by SinisterRectus** [comment]
That's strange, because I get the following, and it does not terminate.

![image](http://i.imgur.com/Ke2dSQ0.png)

In the future, I will probably have to add permissions checking. For now, I may tweak the specific getBannedUsers method to see if it helps. I will let you know if I come up with anything good.

**Comment by SinisterRectus** [comment]
I patched [server.lua](https://github.com/SinisterRectus/Discordia/blob/53ba3ef99817d9516ddc7be345abbbdbe3b82580/discordia/classes/discord/server.lua). Copy the new code into your old file and let me know if this fixes your issue.

**Comment by Nik-mmzd** [comment]
@SinisterRectus big thanks, all OK :)
