### ISSUE TITLE
Previous content of updated message

### ISSUE THREAD

**Issue by danshat** [SinisterRectus/Discordia#95]
Hi! I noticed there is no actual field in Message class for previous content of updated (edited) message (such feature was implemented in one of discord libraries). If this is possible, how can I retrieve it? Maybe through bot's message cache somehow? If this is impossible in current version of Discordia, then it is a suggestion, I suppose. Thank you!

**Comment by truemedian** [comment]
message.oldContent, not currently documented

**Comment by danshat** [comment]
Works fine, thank you again.
