### ISSUE TITLE
Access Denied?!

### ISSUE THREAD

**Issue by JaredMFProgramming** [SinisterRectus/Discordia#96]
Hey there.

I tried to launch my bots, but this happened:

> 2018-01-05 21:54:57 | [INFO]    | Discordia 2.2.0
2018-01-05 21:54:57 | [INFO]    | Connecting to Discord...
2018-01-05 21:54:57 | [ERROR]   | 401 - UNAUTHORIZED : GET https://discordapp.com/api/v7/users/@me
2018-01-05 21:54:57 | [ERROR]   | Could not authenticate, check token: HTTP Error 0 : 401: Unauthorized

Where did I go wrong? :(

**Comment by SinisterRectus** [comment]
Did you check your token.

**Comment by JaredMFProgramming** [comment]
I checked my token, and it was the matching one.

**Comment by SinisterRectus** [comment]
Did you prefix it with `Bot `?

**Comment by JaredMFProgramming** [comment]
I can't say I did, but why?

**Comment by SinisterRectus** [comment]
Because the Discord API requires it and I designed Discordia 2.0 in such a way where the prefix is not automatically added.

**Comment by JaredMFProgramming** [comment]
Oh, okay.

Sorry for misunderstanding.

**Comment by SinisterRectus** [comment]
Refer to the main example for the formatting <https://github.com/SinisterRectus/Discordia#example>

**Comment by JaredMFProgramming** [comment]
I see the example, but I don't have permission to access the API.

**Comment by SinisterRectus** [comment]
Not enough information. Test the token with a different Discord library.

**Comment by DragonStrike406** [comment]
I had same issue and here is your solution:
client:run("Bot <TOKEN>")
add this at the beggining of your code and replace the <TOKEN> with your bot token. This will solve the issue. Make sure there is space between Bot and your token. If this doesn't work then I have no idea what else is causing the issue.

**Comment by jhonny-papallom** [comment]
Same problem:

```
2018-01-09 18:33:26 | [INFO]    | Discordia 2.2.0
2018-01-09 18:33:26 | [INFO]    | Connecting to Discord...
2018-01-09 18:33:26 | [ERROR]   | 401 - UNAUTHORIZED : GET https://discordapp.com/api/v7/users/@me
2018-01-09 18:33:26 | [ERROR]   | Could not authenticate, check token: HTTP Error 0 : 401: Unauthorized
```
I've tried:
```
local discordia = require('discordia')
local client = discordia.Client()

client:on('ready', function()
	print('Logged in as '.. client.user.username)
end)

client:on('messageCreate', function(message)
	if message.content == '!ping' then
		message.channel:send('Pong!')
	end
end)

client:run('Bot And.My.Token')
```
and ``client:run('Only.my.Token')``

**Comment by JohnnyMorganz** [comment]
If you've done everything above then you shouldn't be getting an issue. Prefixing with `Bot` is correct.
Make sure you are using the **Bot Token** rather than the **Client Secret**

**Comment by jhonny-papallom** [comment]
@JohnnyMorganz 
I'm using the **Bot Token**, but doesn't work.

**Comment by Tigerism** [comment]
update discordia and the deps

**Comment by DannehSC** [comment]
discord.gg/discord-api
Join here and go to #lua-discordia

**Comment by trumpCoder** [comment]
Hello, this issue has been fixed per https://github.com/SinisterRectus/Discordia/pull/101

**Comment by SinisterRectus** [comment]
There is no issue in Discordia's authentication flow. The large majority of users are able to use it. As I said earlier, check your token in another Discord library.

**Comment by jhonny-papallom** [comment]
> 2018-01-11 11:25:43 | [INFO]    | Discordia 2.2.0
> 2018-01-11 11:25:43 | [INFO]    | Connecting to Discord...
> 2018-01-11 11:25:44 | [INFO]    | Authenticated as Bot#666
> 2018-01-11 11:25:44 | [INFO]    | Launching shard 0 (1 out of 1)...
> 2018-01-11 11:25:44 | [INFO]    | Shard 0 : Connected to wss://gateway.discord.gg
> 2018-01-11 11:25:44 | [INFO]    | Shard 0 : Received HELLO (gateway-prd-main-4tn3)
> 2018-01-11 11:25:44 | [INFO]    | Shard 0 : Received READY (gateway-prd-main-4tn3, discord-sessions-prd-1-11)


```lua
local discordia = require('discordia')
local client = discordia.Client()


client:on('ready', function()
	print('Logged in as '.. client.user.username)
	client:setGame("tests")
end)

client:on('messageCreate', function(message)
	if message.content == 'w-ping' then
		message.channel:send('Pong!')
    end
    
end)
client:run('Bot My.TOKEN') -- do i need to explain why this isn't my token?
```
I just run two times and the "gateway.json" was created.

**Comment by dato2003** [comment]
Well in my case I just added Bot and it worked
