### ISSUE TITLE
Unexpected Disconnection

### ISSUE THREAD

**Issue by Lautenschlager-id** [SinisterRectus/Discordia#97]
Hello!

I cannot connect my bots on Discord anymore.
This is the message that appears:
![screenshot_1](https://user-images.githubusercontent.com/26045253/34656063-391feb9c-f3fb-11e7-93f3-b95588d86496.png)

The token is correct..
client:run('Bot the_token_is_here')

I don't know what to do :cry:

**Comment by SinisterRectus** [comment]
Update Discordia. Remove the old version and its dependencies and install a new copy.

**Comment by Lautenschlager-id** [comment]
Wow! That actually worked.
I had been searching an explanation for week lol.
Thank you :)
