### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by Lautenschlager-id** [SinisterRectus/Discordia#98]
Hello!
I'm new at bot development, I'm sorry for any misunderstanding of terms.

I'm looking for a method to change my current channel (or guild)
For example, I sent the message "hi" at #channel1 and the bot must send the answer at #channel2

Is it possible like

```Lua
if message.content == "!new_chat" then
GuildTextChannel.topic("second_channel")
message.channel:send("hi")
end
```

? :P

**Comment by DannehSC** [comment]
Can you please join discord.gg/discord-api so we can help easier?
